/** Closed Backup Lite IPC failures. Detailed archive content never crosses IPC. */
export const backupErrorCodes = {
  BUSY: 'BACKUP_BUSY',
  SENDER_NOT_ALLOWED: 'BACKUP_SENDER_NOT_ALLOWED',
  ARCHIVE_REJECTED: 'BACKUP_ARCHIVE_REJECTED',
  RESTORE_INCOMPATIBLE: 'BACKUP_RESTORE_INCOMPATIBLE',
  RESTORE_STATE: 'BACKUP_RESTORE_STATE',
  STORAGE_UNAVAILABLE: 'BACKUP_STORAGE_UNAVAILABLE',
  EXPORT_DESTINATION: 'BACKUP_EXPORT_DESTINATION'
} as const
