/** Knowledge-domain IpcApi error codes. Import directly from this module on both sides. */
export const knowledgeErrorCodes = {
  /** The requested knowledge-managed file or captured URL snapshot cannot provide a preview path. */
  SOURCE_PATH_UNAVAILABLE: 'KNOWLEDGE_SOURCE_PATH_UNAVAILABLE',
  EXTERNAL_CONNECTION_NOT_FOUND: 'KNOWLEDGE_EXTERNAL_CONNECTION_NOT_FOUND',
  EXTERNAL_CONNECTION_IN_USE: 'KNOWLEDGE_EXTERNAL_CONNECTION_IN_USE',
  FEISHU_REGISTRATION_FAILED: 'KNOWLEDGE_FEISHU_REGISTRATION_FAILED',
  FEISHU_AUTHORIZATION_FAILED: 'KNOWLEDGE_FEISHU_AUTHORIZATION_FAILED',
  FEISHU_SCOPE_MISSING: 'KNOWLEDGE_FEISHU_SCOPE_MISSING',
  FEISHU_AUTOMATIC_SCOPE_MISMATCH: 'KNOWLEDGE_FEISHU_AUTOMATIC_SCOPE_MISMATCH',
  FEISHU_IDENTITY_CONFLICT: 'KNOWLEDGE_FEISHU_IDENTITY_CONFLICT',
  FEISHU_IDENTITY_UNVERIFIABLE: 'KNOWLEDGE_FEISHU_IDENTITY_UNVERIFIABLE',
  FEISHU_INVALID_SCOPE_URL: 'KNOWLEDGE_FEISHU_INVALID_SCOPE_URL',
  FEISHU_RESOURCE_PERMISSION_DENIED: 'KNOWLEDGE_FEISHU_RESOURCE_PERMISSION_DENIED',
  FEISHU_SCOPE_NOT_FOUND: 'KNOWLEDGE_FEISHU_SCOPE_NOT_FOUND',
  FEISHU_UNSUPPORTED_RESOURCE: 'KNOWLEDGE_FEISHU_UNSUPPORTED_RESOURCE',
  FEISHU_PROVIDER_UNAVAILABLE: 'KNOWLEDGE_FEISHU_PROVIDER_UNAVAILABLE',
  FEISHU_INVALID_PROVIDER_RESPONSE: 'KNOWLEDGE_FEISHU_INVALID_PROVIDER_RESPONSE',
  EXTERNAL_CREDENTIAL_UNAVAILABLE: 'KNOWLEDGE_EXTERNAL_CREDENTIAL_UNAVAILABLE',
  EXTERNAL_REAUTHORIZATION_REQUIRED: 'KNOWLEDGE_EXTERNAL_REAUTHORIZATION_REQUIRED',
  EXTERNAL_RUNTIME_STOPPED: 'KNOWLEDGE_EXTERNAL_RUNTIME_STOPPED',
  EXTERNAL_SOURCE_CONFLICT: 'KNOWLEDGE_EXTERNAL_SOURCE_CONFLICT',
  EXTERNAL_SOURCE_TARGET_UNAVAILABLE: 'KNOWLEDGE_EXTERNAL_SOURCE_TARGET_UNAVAILABLE'
} as const
