/** Knowledge-domain IpcApi error codes. Import directly from this module on both sides. */
export const knowledgeErrorCodes = {
  /** The requested knowledge-managed file or captured URL snapshot cannot provide a preview path. */
  SOURCE_PATH_UNAVAILABLE: 'KNOWLEDGE_SOURCE_PATH_UNAVAILABLE',
  EXTERNAL_CONNECTION_NOT_FOUND: 'KNOWLEDGE_EXTERNAL_CONNECTION_NOT_FOUND',
  FEISHU_REGISTRATION_FAILED: 'KNOWLEDGE_FEISHU_REGISTRATION_FAILED',
  FEISHU_AUTHORIZATION_FAILED: 'KNOWLEDGE_FEISHU_AUTHORIZATION_FAILED',
  FEISHU_SCOPE_MISSING: 'KNOWLEDGE_FEISHU_SCOPE_MISSING',
  FEISHU_AUTOMATIC_SCOPE_MISMATCH: 'KNOWLEDGE_FEISHU_AUTOMATIC_SCOPE_MISMATCH',
  FEISHU_IDENTITY_CONFLICT: 'KNOWLEDGE_FEISHU_IDENTITY_CONFLICT',
  FEISHU_IDENTITY_UNVERIFIABLE: 'KNOWLEDGE_FEISHU_IDENTITY_UNVERIFIABLE',
  EXTERNAL_CREDENTIAL_UNAVAILABLE: 'KNOWLEDGE_EXTERNAL_CREDENTIAL_UNAVAILABLE',
  EXTERNAL_REAUTHORIZATION_REQUIRED: 'KNOWLEDGE_EXTERNAL_REAUTHORIZATION_REQUIRED',
  EXTERNAL_RUNTIME_STOPPED: 'KNOWLEDGE_EXTERNAL_RUNTIME_STOPPED'
} as const
