/** Notes-relocation IpcApi error codes. Import on main and renderer when branching on failures. */
export const notesRelocationErrorCodes = {
  NOTES_RELOCATION_FAILED: 'NOTES_RELOCATION_FAILED',
  NOTES_RELOCATION_INVALID: 'NOTES_RELOCATION_INVALID',
  NOTES_RELOCATION_MERGE_CONFLICT: 'NOTES_RELOCATION_MERGE_CONFLICT',
  NOTES_RELOCATION_TARGET_NOT_EMPTY: 'NOTES_RELOCATION_TARGET_NOT_EMPTY',
  NOTES_RELOCATION_VERIFY_FAILED: 'NOTES_RELOCATION_VERIFY_FAILED',
  NOTES_RELOCATION_FLUSH_FAILED: 'NOTES_RELOCATION_FLUSH_FAILED',
  NOTES_RELOCATION_IN_PROGRESS: 'NOTES_RELOCATION_IN_PROGRESS'
} as const
