export const ProviderBalanceErrorCode = {
  UNSUPPORTED: 'BALANCE_UNSUPPORTED',
  AUTH: 'BALANCE_AUTH',
  RATE_LIMIT: 'BALANCE_RATE_LIMIT',
  NETWORK: 'BALANCE_NETWORK',
  RESPONSE: 'BALANCE_RESPONSE',
  CONFIG: 'BALANCE_CONFIG'
} as const
