/**
 * @file SettingsSearchConfig.ts
 * @description Automatically generated by scripts/generate-settings-search-index.ts
 * @caution DO NOT EDIT MANUALLY
 */

export const SEARCH_EXCLUDED_PREFIXES = [
  'settings.tool.websearch.tavily.api_key',
  'settings.data.local.minute_interval',
  'settings.data.local.hour_interval',
  'settings.data.webdav.minute_interval',
  'settings.data.webdav.hour_interval',
  'settings.tool.preprocess.mac_system_ocr_options',
  'memory.wait.settings',
  'settings.data.app_knowledge.remove_all_confirm'
]

export const TITLE_TO_ROUTE: Record<string, string> = {
  'settings.provider.title': '/settings/provider',
  'settings.model': '/settings/model',
  'settings.general.label': '/settings/general',
  'settings.display.title': '/settings/display',
  'settings.data.title': '/settings/data',
  'settings.mcp.title': '/settings/mcp',
  'settings.tool.websearch.title': '/settings/websearch',
  'memory.title': '/settings/memory',
  'apiServer.title': '/settings/api-server',
  'settings.tool.preprocess.title': '/settings/docprocess',
  'settings.quickPhrase.title': '/settings/quickphrase',
  'settings.shortcuts.title': '/settings/shortcut',
  'settings.quickAssistant.title': '/settings/quickAssistant',
  'selection.name': '/settings/selectionAssistant',
  'settings.about.label': '/settings/about'
}

export const SUBMENU_KEY_MAP: Record<string, string> = {
  'settings.data.data.title': 'data',
  'settings.data.local.title': 'local_backup',
  'settings.data.webdav.title': 'webdav',
  'settings.data.nutstore.title': 'nutstore',
  'settings.data.s3.title.label': 's3',
  'settings.data.import_settings.title': 'import_settings',
  'settings.data.export_menu.title': 'export_menu',
  'settings.data.markdown_export.title': 'markdown_export',
  'settings.data.notion.title': 'notion',
  'settings.data.yuque.title': 'yuque',
  'settings.data.joplin.title': 'joplin',
  'settings.data.obsidian.title': 'obsidian',
  'settings.data.siyuan.title': 'siyuan'
}

export const SEARCH_INDEX: Record<string, string[] | Record<string, string[]>> = {
  'settings.provider.title': [
    // 模型服务
    'common.delete', // 删除
    'common.edit', // 编辑
    'provider.302ai', // 302.AI
    'provider.ai-gateway', // Vercel AI Gateway
    'provider.aihubmix', // AiHubMix
    'provider.aionly', // 唯一AI (AiOnly)
    'provider.alayanew', // Alaya NeW
    'provider.anthropic', // Anthropic
    'provider.aws-bedrock', // AWS Bedrock
    'provider.azure-openai', // Azure OpenAI
    'provider.baichuan', // 百川
    'provider.baidu-cloud', // 百度云千帆
    'provider.burncloud', // BurnCloud
    'provider.cephalon', // Cephalon
    'provider.cerebras', // Cerebras AI
    'provider.cherryin', // CherryIN
    'provider.copilot', // GitHub Copilot
    'provider.dashscope', // 阿里云百炼
    'provider.deepseek', // 深度求索
    'provider.dmxapi', // DMXAPI
    'provider.doubao', // 火山引擎
    'provider.fireworks', // Fireworks
    'provider.gemini', // Gemini
    'provider.gitee-ai', // 模力方舟
    'provider.github', // GitHub Models
    'provider.gpustack', // GPUStack
    'provider.grok', // Grok
    'provider.groq', // Groq
    'provider.huggingface', // Hugging Face
    'provider.hunyuan', // 腾讯混元
    'provider.hyperbolic', // Hyperbolic
    'provider.infini', // 无问芯穹
    'provider.jina', // Jina
    'provider.lanyun', // 蓝耘科技
    'provider.lmstudio', // LM Studio
    'provider.longcat', // 龙猫
    'provider.mimo', // Xiaomi MiMo
    'provider.minimax', // MiniMax
    'provider.mistral', // Mistral
    'provider.modelscope', // ModelScope 魔搭
    'provider.moonshot', // 月之暗面
    'provider.new-api', // New API
    'provider.nvidia', // 英伟达
    'provider.o3', // O3
    'provider.ocoolai', // ocoolAI
    'provider.ollama', // Ollama
    'provider.openai', // OpenAI
    'provider.openrouter', // OpenRouter
    'provider.ovms', // Intel OVMS
    'provider.perplexity', // Perplexity
    'provider.ph8', // PH8 大模型开放平台
    'provider.poe', // Poe
    'provider.ppio', // PPIO 派欧云
    'provider.qiniu', // 七牛云 AI 推理
    'provider.qwenlm', // QwenLM
    'provider.silicon', // 硅基流动
    'provider.sophnet', // SophNet
    'provider.stepfun', // 阶跃星辰
    'provider.tencent-cloud-ti', // 腾讯云 TI
    'provider.together', // Together
    'provider.tokenflux', // TokenFlux
    'provider.vertexai', // Vertex AI
    'provider.voyageai', // Voyage AI
    'provider.xirang', // 天翼云息壤
    'provider.yi', // 零一万物
    'provider.zhinao', // 360 智脑
    'provider.zhipu', // 智谱开放平台
    'settings.models.provider_key_add_failed_by_invalid_data', // 添加服务商 API 密钥失败，数据格式错误
    'settings.models.provider_key_added', // 成功为 {{provider}} 添加 API 密钥
    'settings.provider.delete.content', // 确定要删除此模型提供商吗？
    'settings.provider.delete.title', // 删除提供商
    'settings.provider.notes.title', // 模型备注
    'settings.provider.search' // 搜索模型平台...
  ],
  'settings.model': [
    // 默认模型
    'settings.models.default_assistant_model', // 默认助手模型
    'settings.models.quick_model.label', // 快速模型
    'settings.models.translate_model' // 翻译模型
  ],
  'settings.general.label': [
    // 常规设置
    'common.language', // 语言
    'settings.developer.enable_developer_mode', // 启用开发者模式
    'settings.developer.title', // 开发者模式
    'settings.general.spell_check.label', // 拼写检查
    'settings.general.title', // 常规设置
    'settings.hardware_acceleration.title', // 禁用硬件加速
    'settings.launch.onboot', // 开机自动启动
    'settings.launch.title', // 启动
    'settings.launch.totray', // 启动时最小化到托盘
    'settings.notification.assistant', // 助手消息
    'settings.notification.backup', // 备份
    'settings.notification.knowledge_embed', // 知识库
    'settings.notification.title', // 通知设置
    'settings.privacy.enable_privacy_mode', // 匿名发送错误报告和数据统计
    'settings.privacy.title', // 隐私设置
    'settings.proxy.mode.system', // 系统代理
    'settings.proxy.mode.title', // 代理模式
    'settings.tray.onclose', // 关闭时最小化到托盘
    'settings.tray.show', // 显示托盘图标
    'settings.tray.title' // 托盘
  ],
  'settings.display.title': [
    // 显示设置
    'settings.advanced.auto_switch_to_topics', // 自动切换到话题
    'settings.assistant.icon.type.emoji', // Emoji 表情
    'settings.assistant.icon.type.label', // 模型图标类型
    'settings.assistant.icon.type.model', // 模型图标
    'settings.assistant.icon.type.none', // 不显示
    'settings.display.assistant.title', // 助手设置
    'settings.display.custom.css.cherrycss', // 从 cherrycss.com 获取
    'settings.display.custom.css.label', // 自定义 CSS
    'settings.display.custom.css.placeholder', // /* 这里写自定义 CSS */
    'settings.display.font.code', // 代码字体
    'settings.display.font.default', // 默认
    'settings.display.font.global', // 全局字体
    'settings.display.font.title', // 字体设置
    'settings.display.navbar.position.label', // 导航栏位置
    'settings.display.navbar.position.left', // 左侧
    'settings.display.navbar.position.top', // 顶部
    'settings.display.navbar.title', // 导航栏设置
    'settings.display.topic.title', // 话题设置
    'settings.display.zoom.title', // 缩放设置
    'settings.theme.color_primary', // 主题颜色
    'settings.theme.dark', // 深色
    'settings.theme.light', // 浅色
    'settings.theme.system', // 系统
    'settings.theme.title', // 主题
    'settings.topic.pin_to_top', // 固定话题置顶
    'settings.topic.position.label', // 话题位置
    'settings.topic.position.left', // 左侧
    'settings.topic.position.right', // 右侧
    'settings.topic.show.time', // 显示话题时间
    'settings.zoom.title' // 缩放
  ],
  'settings.data.title': {
    // 数据设置
    'settings.data.data.title': [
      // 数据目录
      'settings.data.app_data.label', // 应用数据
      'settings.data.app_data.open', // 打开目录
      'settings.data.app_data.select_error_in_app_path', // 新路径与应用安装路径相同，请选择其他路径
      'settings.data.app_data.select_error_root_path', // 新路径不能是根路径
      'settings.data.app_data.select_error_same_path', // 新路径与旧路径相同，请选择其他路径
      'settings.data.app_data.select_error_write_permission', // 新路径没有写入权限
      'settings.data.app_knowledge.button.delete', // 删除文件
      'settings.data.app_knowledge.label', // 知识库文件
      'settings.data.app_logs.button', // 打开日志
      'settings.data.app_logs.label', // 应用日志
      'settings.data.backup.skip_file_data_help', // 备份时跳过备份图片、知识库等数据文件，仅备份聊天记录和设置。减少空间占用，加快备份速度
      'settings.data.backup.skip_file_data_title', // 精简备份
      'settings.data.clear_cache.button', // 清除缓存
      'settings.data.clear_cache.confirm', // 清除缓存将删除应用缓存的数据，包括小程序数据。此操作不可恢复，是否继续？
      'settings.data.clear_cache.success', // 缓存清除成功
      'settings.data.clear_cache.title', // 清除缓存
      'settings.data.data.title', // 数据目录
      'settings.data.export_menu.title', // 导出菜单设置
      'settings.data.export_to_phone.lan.title', // 局域网传输
      'settings.data.export_to_phone.title', // 导出至手机
      'settings.data.import_settings.title', // 导入外部应用数据
      'settings.data.local.title', // 本地备份
      'settings.data.markdown_export.title', // Markdown 导出
      'settings.data.notion.title', // Notion 设置
      'settings.data.nutstore.title', // 坚果云配置
      'settings.data.s3.title.label', // S3 兼容存储
      'settings.data.title', // 数据设置
      'settings.data.webdav.title', // WebDAV
      'settings.data.yuque.title', // 语雀配置
      'settings.general.backup.button', // 备份
      'settings.general.backup.title', // 数据备份与恢复
      'settings.general.reset.title', // 重置数据
      'settings.general.restore.button' // 恢复
    ],
    'settings.data.local.title': [
      // 本地备份
      'common.browse', // 浏览
      'common.clear', // 清除
      'settings.data.backup.skip_file_data_help', // 备份时跳过备份图片、知识库等数据文件，仅备份聊天记录和设置。减少空间占用，加快备份速度
      'settings.data.backup.skip_file_data_title', // 精简备份
      'settings.data.local.autoSync.label', // 自动备份
      'settings.data.local.autoSync.off', // 关闭
      'settings.data.local.backup.button', // 本地备份
      'settings.data.local.directory.label', // 备份目录
      'settings.data.local.directory.placeholder', // 请选择备份目录
      'settings.data.local.maxBackups.label', // 最大备份数
      'settings.data.local.maxBackups.unlimited', // 无限制
      'settings.data.local.restore.button', // 备份文件管理
      'settings.data.local.title' // 本地备份
    ],
    'settings.data.webdav.title': [
      // WebDAV
      'settings.data.backup.skip_file_data_help', // 备份时跳过备份图片、知识库等数据文件，仅备份聊天记录和设置。减少空间占用，加快备份速度
      'settings.data.backup.skip_file_data_title', // 精简备份
      'settings.data.local.maxBackups.unlimited', // 无限制
      'settings.data.webdav.autoSync.label', // 自动备份
      'settings.data.webdav.autoSync.off', // 关闭
      'settings.data.webdav.backup.button', // 备份到 WebDAV
      'settings.data.webdav.disableStream.help', // 开启后，将文件加载到内存中再上传，可解决部分WebDAV服务不兼容chunked上传的问题，但会增加内存占用。
      'settings.data.webdav.disableStream.title', // 禁用流式上传
      'settings.data.webdav.host.label', // WebDAV 地址
      'settings.data.webdav.host.placeholder', // http://localhost:8080
      'settings.data.webdav.maxBackups', // 最大备份数
      'settings.data.webdav.password', // WebDAV 密码
      'settings.data.webdav.path.label', // WebDAV 路径
      'settings.data.webdav.path.placeholder', // /backup
      'settings.data.webdav.restore.button', // 从 WebDAV 恢复
      'settings.data.webdav.title', // WebDAV
      'settings.data.webdav.user' // WebDAV 用户名
    ],
    'settings.data.nutstore.title': [
      // 坚果云配置
      'settings.data.nutstore.login.button', // 登录
      'settings.data.nutstore.notLogin', // 未登录
      'settings.data.nutstore.title' // 坚果云配置
    ],
    'settings.data.s3.title.label': [
      // S3 兼容存储
      'settings.data.s3.accessKeyId.label', // Access Key ID
      'settings.data.s3.accessKeyId.placeholder', // Access Key ID
      'settings.data.s3.autoSync.label', // 自动同步
      'settings.data.s3.autoSync.off', // 关闭
      'settings.data.s3.backup.button', // 立即备份
      'settings.data.s3.backup.manager.button', // 管理备份
      'settings.data.s3.backup.operation', // 备份操作
      'settings.data.s3.bucket.label', // 存储桶
      'settings.data.s3.bucket.placeholder', // Bucket, 例如: example
      'settings.data.s3.endpoint.label', // API 地址
      'settings.data.s3.endpoint.placeholder', // https://s3.example.com
      'settings.data.s3.maxBackups.label', // 最大备份数
      'settings.data.s3.maxBackups.unlimited', // 不限
      'settings.data.s3.region.label', // 区域
      'settings.data.s3.region.placeholder', // Region, 例如: us-east-1
      'settings.data.s3.root.label', // 备份目录（可选）
      'settings.data.s3.root.placeholder', // 例如：/cherry-studio
      'settings.data.s3.secretAccessKey.label', // Secret Access Key
      'settings.data.s3.secretAccessKey.placeholder', // Secret Access Key
      'settings.data.s3.skipBackupFile.help', // 开启后备份时将跳过文件数据，仅备份配置信息，显著减小备份文件体积
      'settings.data.s3.skipBackupFile.label', // 精简备份
      'settings.data.s3.title.label' // S3 兼容存储
    ],
    'settings.data.import_settings.title': [
      // 导入外部应用数据
      'settings.data.import_settings.button', // 导入文件
      'settings.data.import_settings.chatgpt', // 导入 ChatGPT 数据
      'settings.data.import_settings.title' // 导入外部应用数据
    ],
    'settings.data.export_menu.title': [
      // 导出菜单设置
      'settings.data.export_menu.docx', // 导出为 Word
      'settings.data.export_menu.image', // 导出为图片
      'settings.data.export_menu.joplin', // 导出到 Joplin
      'settings.data.export_menu.markdown', // 导出为 Markdown
      'settings.data.export_menu.markdown_reason', // 导出为 Markdown（包含思考）
      'settings.data.export_menu.notion', // 导出到 Notion
      'settings.data.export_menu.obsidian', // 导出到 Obsidian
      'settings.data.export_menu.plain_text', // 复制为纯文本
      'settings.data.export_menu.siyuan', // 导出到思源笔记
      'settings.data.export_menu.title', // 导出菜单设置
      'settings.data.export_menu.yuque' // 导出到语雀
    ],
    'settings.data.markdown_export.title': [
      // Markdown 导出
      'settings.data.markdown_export.exclude_citations.help', // 导出 Markdown 时排除引用和参考文献，仅保留主要内容
      'settings.data.markdown_export.exclude_citations.title', // 不导出引用内容
      'settings.data.markdown_export.force_dollar_math.help', // 开启后，导出 Markdown 时会将强制使用 $$ 来标记 LaTeX 公式。注意：该项也会影响所有通过 Markdown 导出的方式，如 Notion、语雀等
      'settings.data.markdown_export.force_dollar_math.title', // 强制使用 $$ 来标记 LaTeX 公式
      'settings.data.markdown_export.path', // 默认导出路径
      'settings.data.markdown_export.path_placeholder', // 导出路径
      'settings.data.markdown_export.select', // 选择
      'settings.data.markdown_export.show_model_name.help', // 开启后，导出 Markdown 时会显示模型名称。注意：该项也会影响所有通过 Markdown 导出的方式，如 Notion、语雀等。
      'settings.data.markdown_export.show_model_name.title', // 导出时使用模型名称
      'settings.data.markdown_export.show_model_provider.help', // 在导出 Markdown 时显示模型供应商，如 OpenAI、Gemini 等
      'settings.data.markdown_export.show_model_provider.title', // 显示模型供应商
      'settings.data.markdown_export.standardize_citations.help', // 开启后，导出 Markdown 时会将引用标记转换为标准 Markdown 脚注格式 [^1]，并格式化引用列表
      'settings.data.markdown_export.standardize_citations.title', // 标准化引用格式
      'settings.data.markdown_export.title', // Markdown 导出
      'settings.data.message_title.use_topic_naming.help', // 开启后，使用快速模型为导出的消息命名标题。该项也会影响所有通过 Markdown 导出的方式
      'settings.data.message_title.use_topic_naming.title' // 使用快速模型为导出的消息命名标题
    ],
    'settings.data.notion.title': [
      // Notion 设置
      'settings.data.notion.api_key', // Notion 密钥
      'settings.data.notion.api_key_placeholder', // 请输入 Notion 密钥
      'settings.data.notion.check.button', // 检测
      'settings.data.notion.database_id', // Notion 数据库 ID
      'settings.data.notion.database_id_placeholder', // 请输入 Notion 数据库 ID
      'settings.data.notion.export_reasoning.help', // 开启后，导出到 Notion 时会包含思维链内容。
      'settings.data.notion.export_reasoning.title', // 导出时包含思维链
      'settings.data.notion.page_name_key', // 页面标题字段名
      'settings.data.notion.page_name_key_placeholder', // 请输入页面标题字段名，默认为 Name
      'settings.data.notion.title' // Notion 设置
    ],
    'settings.data.yuque.title': [
      // 语雀配置
      'settings.data.yuque.check.button', // 检测
      'settings.data.yuque.repo_url', // 知识库 URL
      'settings.data.yuque.repo_url_placeholder', // https://www.yuque.com/username/xxx
      'settings.data.yuque.title', // 语雀配置
      'settings.data.yuque.token', // 语雀 Token
      'settings.data.yuque.token_placeholder' // 请输入语雀 Token
    ],
    'settings.data.joplin.title': [
      // Joplin 配置
      'settings.data.joplin.check.button', // 检测
      'settings.data.joplin.export_reasoning.help', // 开启后，导出到 Joplin 时会包含思维链内容。
      'settings.data.joplin.export_reasoning.title', // 导出时包含思维链
      'settings.data.joplin.title', // Joplin 配置
      'settings.data.joplin.token', // Joplin 授权令牌
      'settings.data.joplin.token_placeholder', // 请输入 Joplin 授权令牌
      'settings.data.joplin.url', // Joplin 剪裁服务监听 URL
      'settings.data.joplin.url_placeholder' // http://127.0.0.1:41184/
    ],
    'settings.data.obsidian.title': [
      // Obsidian 配置
      'settings.data.obsidian.default_vault', // 默认 Obsidian 仓库
      'settings.data.obsidian.default_vault_no_vaults', // 未找到 Obsidian 仓库
      'settings.data.obsidian.title' // Obsidian 配置
    ],
    'settings.data.siyuan.title': [
      // 思源笔记配置
      'settings.data.siyuan.api_url', // API 地址
      'settings.data.siyuan.api_url_placeholder', // 例如：http://127.0.0.1:6806
      'settings.data.siyuan.box_id', // 笔记本 ID
      'settings.data.siyuan.box_id_placeholder', // 请输入笔记本 ID
      'settings.data.siyuan.check.button', // 检测
      'settings.data.siyuan.root_path', // 文档根路径
      'settings.data.siyuan.root_path_placeholder', // 例如：/CherryStudio
      'settings.data.siyuan.title', // 思源笔记配置
      'settings.data.siyuan.token.label', // API 令牌
      'settings.data.siyuan.token_placeholder' // 请输入思源笔记令牌
    ]
  },
  'settings.mcp.title': [
    // MCP 服务器
    'common.add', // 添加
    'common.edit', // 编辑
    'common.no_results', // 无结果
    'settings.mcp.addServer.create', // 快速创建
    'settings.mcp.addServer.importFrom.dxt', // 导入 DXT 包
    'settings.mcp.addServer.importFrom.json', // 从 JSON 导入
    'settings.mcp.addSuccess', // 服务器添加成功
    'settings.mcp.builtinServers', // 内置服务器
    'settings.mcp.deleteError', // 删除服务器失败
    'settings.mcp.deleteServer', // 删除服务器
    'settings.mcp.deleteServerConfirm', // 确定要删除此服务器吗？
    'settings.mcp.deleteSuccess', // 服务器删除成功
    'settings.mcp.discover', // 发现
    'settings.mcp.findMore', // 更多 MCP
    'settings.mcp.marketplaces', // 市场
    'settings.mcp.more.awesome', // 精选的 MCP 服务器列表
    'settings.mcp.more.composio', // Composio MCP 开发工具
    'settings.mcp.more.glama', // Glama MCP 服务器目录
    'settings.mcp.more.higress', // Higress MCP 服务器
    'settings.mcp.more.mcpso', // MCP 服务器发现平台
    'settings.mcp.more.modelscope', // 魔搭社区 MCP 服务器
    'settings.mcp.more.official', // 官方 MCP 服务器集合
    'settings.mcp.more.pulsemcp', // Pulse MCP 服务器
    'settings.mcp.more.smithery', // Smithery MCP 工具
    'settings.mcp.more.zhipu', // 精选MCP，极速接入
    'settings.mcp.newServer', // MCP 服务器
    'settings.mcp.noServers', // 未配置服务器
    'settings.mcp.providers', // 提供商
    'settings.mcp.requiresConfig', // 需要配置
    'settings.mcp.search.placeholder', // 搜索 MCP 服务器...
    'settings.mcp.search.tooltip', // 搜索 MCP 服务器
    'settings.mcp.servers', // MCP 服务器
    'settings.mcp.startError' // 启动失败
  ],
  'settings.tool.websearch.title': [
    // 网络搜索
    'common.name', // 名称
    'common.save', // 保存
    'settings.general.title', // 常规设置
    'settings.tool.websearch.api_providers', // API 服务商
    'settings.tool.websearch.blacklist', // 黑名单
    'settings.tool.websearch.blacklist_description', // 在搜索结果中不会出现以下网站的结果
    'settings.tool.websearch.blacklist_tooltip', // 请使用以下格式(换行分隔) 匹配模式: *://*.example.com/* 正则表达式: /example\.(net|org)/
    'settings.tool.websearch.compression.method.label', // 压缩方法
    'settings.tool.websearch.compression.method.none', // 不压缩
    'settings.tool.websearch.compression.title', // 搜索结果压缩
    'settings.tool.websearch.default_provider', // 默认搜索引擎
    'settings.tool.websearch.local_providers', // 本地搜索
    'settings.tool.websearch.search_max_result.label', // 搜索结果个数
    'settings.tool.websearch.search_provider', // 搜索服务商
    'settings.tool.websearch.search_with_time', // 搜索包含日期
    'settings.tool.websearch.subscribe', // 黑名单订阅
    'settings.tool.websearch.subscribe_add' // 添加订阅
  ],
  'memory.title': [
    // 全局记忆
    'common.more', // 更多
    'memory.add_first_memory', // 添加您的第一条记忆
    'memory.add_memory', // 添加记忆
    'memory.default_user', // 默认用户
    'memory.global_memory', // 全局记忆
    'memory.no_memories', // 暂无记忆
    'memory.no_memories_description', // 开始添加您的第一条记忆吧
    'memory.search_placeholder', // 搜索记忆...
    'memory.statistics', // 统计
    'memory.total_memories', // 条记忆
    'memory.user_id', // 用户 ID
    'memory.user_management', // 用户管理
    'memory.users' // 用户
  ],
  'apiServer.title': [
    // API 服务器
    'apiServer.actions.regenerate', // 重新生成
    'apiServer.authHeader.title', // 授权标头
    'apiServer.description', // 通过 OpenAI 兼容的 HTTP API 暴露 Cherry Studio 的 AI 功能
    'apiServer.fields.apiKey.description', // 用于 API 访问的安全认证令牌
    'apiServer.fields.apiKey.label', // API 密钥
    'apiServer.fields.port.description', // HTTP 服务器的 TCP 端口号 (1000-65535)
    'apiServer.status.stopped' // 已停止
  ],
  'settings.tool.preprocess.title': [
    // 文档处理
    'settings.mineru.api_key', // MinerU现在提供每日500页的免费额度，您不需要填写密钥。
    'settings.provider.api_host', // API 地址
    'settings.provider.api_key.tip', // 多个密钥使用逗号分隔
    'settings.provider.get_api_key', // 点击这里获取密钥
    'settings.tool.ocr.common.langs', // 支持的语言
    'settings.tool.ocr.image.title', // 图片
    'settings.tool.ocr.image_provider', // OCR 服务提供商
    'settings.tool.ocr.title', // OCR 服务
    'settings.tool.preprocess.provider' // 文档处理服务商
  ],
  'settings.quickPhrase.title': [
    // 快捷短语
  ],
  'settings.shortcuts.title': [
    // 快捷键
    'settings.shortcuts.clear_topic', // 清空消息
    'settings.shortcuts.copy_last_message', // 复制上一条消息
    'settings.shortcuts.edit_last_user_message', // 编辑最后一条用户消息
    'settings.shortcuts.exit_fullscreen', // 退出全屏
    'settings.shortcuts.label', // 按键
    'settings.shortcuts.mini_window', // 快捷助手
    'settings.shortcuts.new_topic', // 新建话题
    'settings.shortcuts.press_shortcut', // 按下快捷键
    'settings.shortcuts.rename_topic', // 重命名话题
    'settings.shortcuts.reset_defaults', // 重置默认快捷键
    'settings.shortcuts.search_message', // 搜索消息
    'settings.shortcuts.search_message_in_chat', // 在当前对话中搜索消息
    'settings.shortcuts.selection_assistant_select_text', // 划词助手：取词
    'settings.shortcuts.selection_assistant_toggle', // 开关划词助手
    'settings.shortcuts.show_app', // 显示 / 隐藏应用
    'settings.shortcuts.show_settings', // 打开设置
    'settings.shortcuts.toggle_new_context', // 清除上下文
    'settings.shortcuts.toggle_show_assistants', // 切换助手显示
    'settings.shortcuts.toggle_show_topics', // 切换话题显示
    'settings.shortcuts.zoom_in', // 放大界面
    'settings.shortcuts.zoom_out', // 缩小界面
    'settings.shortcuts.zoom_reset' // 重置缩放
  ],
  'settings.quickAssistant.title': [
    // 快捷助手
    'settings.quickAssistant.enable_quick_assistant' // 启用快捷助手
  ],
  'selection.name': [
    // 划词助手
    'selection.settings.enable.title', // 启用
    'settings.about.feedback.button' // 反馈
  ],
  'settings.about.label': [
    // 关于我们
    'settings.about.checkUpdate.label', // 检查更新
    'settings.about.contact.button', // 邮件
    'settings.about.contact.title', // 邮件联系
    'settings.about.debug.open', // 打开
    'settings.about.debug.title', // 调试面板
    'settings.about.description', // 一款为创造者而生的 AI 助手
    'settings.about.enterprise.title', // 企业版
    'settings.about.feedback.button', // 反馈
    'settings.about.feedback.title', // 意见反馈
    'settings.about.releases.button', // 查看
    'settings.about.releases.title', // 更新日志
    'settings.about.website.button', // 查看
    'settings.about.website.title', // 官方网站
    'settings.general.auto_check_update.title', // 自动更新
    'settings.general.test_plan.title' // 测试计划
  ]
}
