enableImmutableInstalls: false

httpTimeout: 300000

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.9.1.cjs
npmRegistryServer: https://registry.npmjs.org
npmPublishRegistry: https://registry.npmjs.org
