/**
 * Assistant entity types
 *
 * Assistants represent model + manually assembled context configurations.
 * They store inference parameters, tool references, and context source toggles.
 */

import * as z from 'zod'

// ============================================================================
// Sub-Schemas
// ============================================================================

/** MCP server interaction mode */
const McpModeSchema = z.enum(['disabled', 'auto', 'manual'])
export type McpMode = z.infer<typeof McpModeSchema>

/**
 * Assistant inference settings.
 * Stored as JSON in the database - these are model parameters, not context config.
 */
export const AssistantSettingsSchema = z.object({
  temperature: z.number().optional(),
  topP: z.number().optional(),
  contextCount: z.number().optional(),
  streamOutput: z.boolean().optional(),
  maxTokens: z.number().optional(),
  enableMaxTokens: z.boolean().optional(),
  enableTemperature: z.boolean().optional(),
  enableTopP: z.boolean().optional(),
  reasoning_effort: z.string().optional(),
  qwenThinkMode: z.boolean().optional(),
  toolUseMode: z.enum(['function', 'prompt']).optional(),
  maxToolCalls: z.number().optional(),
  enableMaxToolCalls: z.boolean().optional(),
  /** User-defined model parameters (e.g. {"top_k": 40, "repetition_penalty": 1.1}).
   *  Uses z.unknown() instead of z.json() to avoid non-portable Zod internal type references. */
  customParameters: z.record(z.string(), z.unknown()).optional()
})
export type AssistantSettings = z.infer<typeof AssistantSettingsSchema>

// ============================================================================
// Assistant Entity
// ============================================================================

/**
 * Complete Assistant entity as stored in database.
 *
 * Nullable DB columns are represented as optional (`?`) - the service layer
 * converts SQL NULL to `undefined` so consumers don't need to handle `null`.
 */
export const AssistantSchema = z.object({
  /** Assistant ID (UUID v4, auto-generated by database) */
  id: z.uuidv4(),
  /** Display name */
  name: z.string().min(1),
  /** System prompt text or prompt template ID reference */
  prompt: z.string(),
  /** Emoji icon for UI display */
  emoji: z.string().optional(),
  /** Long-form description */
  description: z.string().optional(),
  /** Inference settings (temperature, topP, etc.) */
  settings: AssistantSettingsSchema.optional(),
  /** MCP server interaction mode */
  mcpMode: McpModeSchema.optional(),
  /** Whether web search is enabled as context source */
  enableWebSearch: z.boolean().optional(),
  /** Whether memory search is enabled as context source */
  enableMemory: z.boolean().optional(),
  /** Creation timestamp (ISO string) */
  createdAt: z.iso.datetime(),
  /** Last update timestamp (ISO string) */
  updatedAt: z.iso.datetime()
})
export type Assistant = z.infer<typeof AssistantSchema>
