/**
 * Tag entity types
 *
 * Tags are user-defined labels that can be applied to various entities
 * (assistants, topics, sessions) via the entity_tag join table.
 */

import * as z from 'zod'

// ============================================================================
// Tag Entity
// ============================================================================

/**
 * Complete Tag entity as returned by the API.
 */
export const TagSchema = z.object({
  /** Tag ID (UUID v4, auto-generated by database) */
  id: z.uuidv4(),
  /** Unique tag name */
  name: z.string().min(1),
  /** Display color (e.g. #FF5733), null if unset */
  color: z
    .string()
    .regex(/^#[0-9a-fA-F]{6}$/)
    .nullable(),
  /** Creation timestamp (ISO string) */
  createdAt: z.iso.datetime(),
  /** Last update timestamp (ISO string) */
  updatedAt: z.iso.datetime()
})
export type Tag = z.infer<typeof TagSchema>

// ============================================================================
// Entity Type Enum
// ============================================================================

/**
 * Entity types that support tagging.
 */
export const TaggableEntityType = z.enum(['assistant', 'topic', 'session'])
export type TaggableEntityType = z.infer<typeof TaggableEntityType>
