/**
 * Generate the per-connection dsh `cordis.yml` composition string.
 *
 * Everything is inlined as concrete JSON-quoted values (no `!!js` tags) — the
 * ONLY env indirections are `apiKeyEnv: CHERRY_DSH_API_KEY` (the secret stays
 * out of the file) and the bridge socket, which the plugin reads from
 * `CHERRY_DSH_BRIDGE_SOCK` directly. Every plugin `name` is resolved to an
 * absolute file URL at generation time: the packaged app runs the composition
 * from a foreign config dir where bare package names are not resolvable.
 */
import { createRequire } from 'node:module'
import { pathToFileURL } from 'node:url'

import type { BridgePermissionMode } from '@cherrystudio/dsh-bridge'
import { isWin } from '@main/core/platform'
import { toAsarUnpackedPath } from '@main/utils/asar'
import type { DshApi } from '@shared/ai/dshModelCompatibility'

import type { DshModelConfig, DshReasoningEffort } from './modelInjection'

const require_ = createRequire(import.meta.url)

/** Resolve a composition plugin specifier to its packaged on-disk entry. */
export function resolveDshPluginPath(specifier: string): string {
  return toAsarUnpackedPath(require_.resolve(specifier))
}

/** Convert a plugin entry path into the URL form required by Node's ESM loader. */
export function toDshPluginUrl(pluginPath: string, windows = isWin): string {
  return pathToFileURL(pluginPath, { windows }).href
}

/** Resolve the `dsh-jsonrpc-agent` runtime bin spawned via `ELECTRON_RUN_AS_NODE`. */
export function resolveDshRuntimeBinPath(): string {
  return resolveDshPluginPath('@deepseek-ai/dsh-sdk-jsonrpc-demo/bin')
}

export interface DshCompositionInput {
  providerName: string
  api: DshApi
  baseUrl: string
  headers?: Record<string, string>
  /** Connection-frozen reasoning level; absent preserves the provider default. */
  reasoning?: DshReasoningEffort
  modelConfig: DshModelConfig
  workspacePath: string
  /** Cherry-owned DSH home used by the durable attachment store. */
  dshRoot: string
  /** JSONL session-persistence root (`feature.agents.dsh.sessions`). */
  sessionsRoot: string
  permissionMode: BridgePermissionMode
  /** Cherry-materialized system prompt; empty string keeps the spine's native persona. */
  persona: string
  /** A workspace `system.md` replaced the native base — drop the dsh identity sentence. */
  customBase: boolean
  /** Canonical dirs of the agent's enabled Cherry-managed skills (composition customSkillDirs). */
  skillDirs: readonly string[]
  /** Platform override for composition contract tests. */
  platform?: NodeJS.Platform
}

/** JSON-quote a YAML scalar — valid YAML double-quoted style, injection-safe. */
const q = (value: string): string => JSON.stringify(value)

function mapLines(indent: string, record: Record<string, string>): string[] {
  return Object.entries(record).map(([key, value]) => `${indent}${q(key)}: ${q(value)}`)
}

function reasoningEffortLines(modelConfig: DshModelConfig): string[] {
  if (modelConfig.reasoningEfforts === false) return [`            reasoningEfforts: false`]
  return [
    `            reasoningEfforts:`,
    ...Object.entries(modelConfig.reasoningEfforts).map(([effort, wireValue]) =>
      wireValue === null ? `              ${effort}:` : `              ${effort}: ${q(wireValue)}`
    )
  ]
}

export function buildDshCompositionYaml(input: DshCompositionInput): string {
  const isWindows = input.platform === undefined ? isWin : input.platform === 'win32'
  const pluginName = (specifier: string) => q(toDshPluginUrl(resolveDshPluginPath(specifier), isWindows))
  const sandboxMode = input.permissionMode === 'bypassPermissions' ? 'danger-full-access' : 'workspace-write'
  const shellExecutor = isWindows ? '@deepseek-ai/dsh-pwsh-sandbox' : '@deepseek-ai/dsh-bash-sandbox'
  const lines: string[] = [
    '# Generated by Cherry Studio for one dsh runtime connection. stdout is JSON-RPC; no stdout loggers.',
    `- id: sdk-jsonrpc-server`,
    `  name: ${pluginName('@deepseek-ai/dsh-sdk-jsonrpc-server')}`,
    `  config:`,
    `    maxTokensAsSuccess: false`,
    ``,
    `- id: llm`,
    `  name: ${pluginName('@deepseek-ai/dsh-llm-pi-ai')}`,
    `  config:`,
    `    providers:`,
    `      ${q(input.providerName)}:`,
    `        apiKeyEnv: ${q('CHERRY_DSH_API_KEY')}`,
    // Google is a catalog-provider reuse: naming its explicit protocol would be rejected by rc.6.
    ...(input.api === 'google-generative-ai' ? [] : [`        api: ${q(input.api)}`]),
    `        baseURL: ${q(input.baseUrl)}`,
    ...(input.headers && Object.keys(input.headers).length
      ? [`        headers:`, ...mapLines('          ', input.headers)]
      : []),
    ...(input.reasoning ? [`        reasoning: ${q(input.reasoning)}`] : []),
    `        models:`,
    `          - id: ${q(input.modelConfig.id)}`,
    ...(input.modelConfig.name ? [`            name: ${q(input.modelConfig.name)}`] : []),
    `            contextWindow: ${input.modelConfig.contextWindow}`,
    `            maxTokens: ${input.modelConfig.maxTokens}`,
    `            input:`,
    ...input.modelConfig.input.map((modality) => `              - ${q(modality)}`),
    ...reasoningEffortLines(input.modelConfig),
    ``,
    // Configless = normal mode: 2 retries for empty/rate-limit/server/timeout/transport,
    // 500ms→10s backoff. The provider profile above sets no `retryPolicy` override.
    `- id: llm-retry`,
    `  name: ${pluginName('@deepseek-ai/dsh-llm-retry')}`,
    ``,
    `- id: sandbox`,
    `  name: ${pluginName('@deepseek-ai/dsh-sandbox-local')}`,
    ``,
    `- id: sandbox-policy`,
    `  name: ${pluginName('@deepseek-ai/dsh-sandbox-policy')}`,
    `  config:`,
    `    mode: ${q(sandboxMode)}`,
    `    workspaceRoot: ${q(input.workspacePath)}`,
    ``,
    `- id: subprocess`,
    `  name: ${pluginName('@deepseek-ai/dsh-subprocess-local')}`,
    ``,
    `- id: shell-executor`,
    `  name: ${pluginName(shellExecutor)}`,
    `  config:`,
    `    cwd: ${q(input.workspacePath)}`,
    ``,
    // policy: ask ALWAYS — bypass is expressed by the bridge plugin's allow-all, never `never`.
    `- id: approval`,
    `  name: ${pluginName('@deepseek-ai/dsh-user-approval')}`,
    `  config:`,
    `    policy: ${q('ask')}`,
    ``,
    `- id: agent-spine`,
    `  name: ${pluginName('@deepseek-ai/dsh-agent-spine-demo')}`,
    `  config:`,
    // dsh interpolates {{var}} strictly at render (unknown refs THROW); Cherry text
    // never uses dsh variables, so break every opener instead of crashing turns.
    ...(input.persona ? [`    persona: ${q(input.persona.replaceAll('{{', '{ {'))}`] : []),
    // A workspace system.md replaces the persona base; drop only the dsh identity
    // sentence — tool-guidance sections stay (mechanics, not persona).
    ...(input.customBase ? [`    includeHarnessIdentity: false`] : []),
    // AGENTS.md/CLAUDE.md are trusted workspace text — parity with pi's `noContextFiles: false`.
    `    workspaceContext:`,
    `      maxBytes: 32768`,
    ...(input.skillDirs.length
      ? [
          `    skills:`,
          `      enabled: true`,
          `      filesystem:`,
          // Fail-closed skill discovery: Cherry owns the root list (pi's noSkills +
          // additionalSkillPaths analogue); membership changes rebuild via the signature.
          `        includeDefaultRoots: false`,
          `        customSkillDirs:`,
          ...input.skillDirs.map((dir) => `          - ${q(dir)}`),
          `        watch: false`
        ]
      : [`    skills:`, `      enabled: false`]),
    ...(isWindows ? [`    toolBash: false`] : [`    toolBash:`, `      enableRunInBackground: false`]),
    `    toolJobs: false`,
    ``,
    ...(isWindows
      ? [
          `- id: shell-env`,
          `  name: ${pluginName('@deepseek-ai/dsh-shell-env')}`,
          `  config:`,
          `    dshHome: ${q(input.dshRoot)}`,
          ``,
          `- id: tool-pwsh`,
          `  name: ${pluginName('@deepseek-ai/dsh-tool-pwsh')}`,
          `  config:`,
          `    enableRunInBackground: false`,
          ``
        ]
      : []),
    `- id: fs`,
    `  name: ${pluginName('@deepseek-ai/dsh-fs-local')}`,
    `  config:`,
    `    cwd: ${q(input.workspacePath)}`,
    ``,
    `- id: attachments`,
    `  name: ${pluginName('@deepseek-ai/dsh-attachment-local')}`,
    `  config:`,
    `    dshHome: ${q(input.dshRoot)}`,
    ``,
    `- id: tool-fs`,
    `  name: ${pluginName('@deepseek-ai/dsh-tool-fs')}`,
    ``,
    `- id: tool-todo`,
    `  name: ${pluginName('@deepseek-ai/dsh-tool-todo')}`,
    `  config:`,
    // Single-active discipline: the composition mounts no background bash/jobs/subagents.
    `    allowParallelInProgress: false`,
    ``,
    // token-meter rejects any config key; session-projection carries its contextBreakdown unit.
    `- id: token-meter`,
    `  name: ${pluginName('@deepseek-ai/dsh-token-meter')}`,
    ``,
    `- id: session-projection`,
    `  name: ${pluginName('@deepseek-ai/dsh-session-projection')}`,
    ``,
    // Both configless: pruner defaults match dsh's base bundle (8192/4096/1024 chars);
    // compaction auto-triggers at 80% of contextWindow and summarizes via the routed model.
    `- id: tool-result-pruner`,
    `  name: ${pluginName('@deepseek-ai/dsh-compaction-tool-result-pruner')}`,
    ``,
    `- id: compaction-basic`,
    `  name: ${pluginName('@deepseek-ai/dsh-compaction-basic')}`,
    ``,
    // Slash commands (host-dispatched over the bridge `command` frame): /compact + /goal.
    `- id: commands`,
    `  name: ${pluginName('@deepseek-ai/dsh-commands')}`,
    ``,
    `- id: command-compact`,
    `  name: ${pluginName('@deepseek-ai/dsh-command-compact')}`,
    ``,
    // Goal domain, model-facing goal tools/prompt section, and same-session continuation.
    // Round turns reach the host as autonomous receive-only turns (adapter beginTurn contract);
    // activation disarms on every resume, so restarts never continue a goal unprompted.
    `- id: goal`,
    `  name: ${pluginName('@deepseek-ai/dsh-goal')}`,
    ``,
    `- id: tool-goal`,
    `  name: ${pluginName('@deepseek-ai/dsh-tool-goal')}`,
    ``,
    `- id: goal-round-driver`,
    `  name: ${pluginName('@deepseek-ai/dsh-goal-round-driver')}`,
    ``,
    `- id: command-goal`,
    `  name: ${pluginName('@deepseek-ai/dsh-command-goal')}`,
    ``,
    `- id: sessions`,
    `  name: ${pluginName('@deepseek-ai/dsh-session-persistence-jsonl')}`,
    `  config:`,
    `    root: ${q(input.sessionsRoot)}`
  ]

  lines.push(``, `- id: cherry-bridge`, `  name: ${pluginName('@cherrystudio/dsh-bridge/plugin')}`, ``)
  return lines.join('\n')
}
