/**
 * Code language list.
 * Data source: linguist-languages
 *
 * ⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️
 *   THIS FILE IS AUTOMATICALLY GENERATED BY A SCRIPT. DO NOT EDIT IT MANUALLY!
 *   Run `yarn update:languages` to update this file.
 * ⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️
 *
 */

type LanguageData = {
  type: string
  aliases?: string[]
  extensions?: string[]
}

export const languages: Record<string, LanguageData> = {
  '1c enterprise': {
    type: 'programming',
    extensions: ['.bsl', '.os']
  },
  '2-dimensional array': {
    type: 'data',
    extensions: ['.2da']
  },
  '4d': {
    type: 'programming',
    extensions: ['.4dm']
  },
  abap: {
    type: 'programming',
    extensions: ['.abap']
  },
  'abap cds': {
    type: 'programming',
    extensions: ['.asddls']
  },
  abnf: {
    type: 'data',
    extensions: ['.abnf']
  },
  actionscript: {
    type: 'programming',
    extensions: ['.as'],
    aliases: ['actionscript 3', 'actionscript3', 'as3']
  },
  ada: {
    type: 'programming',
    extensions: ['.adb', '.ada', '.ads'],
    aliases: ['ada95', 'ada2005']
  },
  'adblock filter list': {
    type: 'data',
    extensions: ['.txt'],
    aliases: ['ad block filters', 'ad block', 'adb', 'adblock']
  },
  'adobe font metrics': {
    type: 'data',
    extensions: ['.afm'],
    aliases: ['acfm', 'adobe composite font metrics', 'adobe multiple font metrics', 'amfm']
  },
  agda: {
    type: 'programming',
    extensions: ['.agda']
  },
  'ags script': {
    type: 'programming',
    extensions: ['.asc', '.ash'],
    aliases: ['ags']
  },
  aidl: {
    type: 'programming',
    extensions: ['.aidl']
  },
  aiken: {
    type: 'programming',
    extensions: ['.ak']
  },
  al: {
    type: 'programming',
    extensions: ['.al']
  },
  alloy: {
    type: 'programming',
    extensions: ['.als']
  },
  'alpine abuild': {
    type: 'programming',
    aliases: ['abuild', 'apkbuild']
  },
  'altium designer': {
    type: 'data',
    extensions: ['.OutJob', '.PcbDoc', '.PrjPCB', '.SchDoc'],
    aliases: ['altium']
  },
  ampl: {
    type: 'programming',
    extensions: ['.ampl', '.mod']
  },
  angelscript: {
    type: 'programming',
    extensions: ['.as', '.angelscript']
  },
  'answer set programming': {
    type: 'programming',
    extensions: ['.lp']
  },
  antlers: {
    type: 'markup',
    extensions: ['.antlers.html', '.antlers.php', '.antlers.xml']
  },
  antlr: {
    type: 'programming',
    extensions: ['.g4']
  },
  apacheconf: {
    type: 'data',
    extensions: ['.apacheconf', '.vhost'],
    aliases: ['aconf', 'apache']
  },
  apex: {
    type: 'programming',
    extensions: ['.cls', '.apex', '.trigger']
  },
  'api blueprint': {
    type: 'markup',
    extensions: ['.apib']
  },
  apl: {
    type: 'programming',
    extensions: ['.apl', '.dyalog']
  },
  'apollo guidance computer': {
    type: 'programming',
    extensions: ['.agc']
  },
  applescript: {
    type: 'programming',
    extensions: ['.applescript', '.scpt'],
    aliases: ['osascript']
  },
  arc: {
    type: 'programming',
    extensions: ['.arc']
  },
  asciidoc: {
    type: 'prose',
    extensions: ['.asciidoc', '.adoc', '.asc']
  },
  asl: {
    type: 'programming',
    extensions: ['.asl', '.dsl']
  },
  'asn.1': {
    type: 'data',
    extensions: ['.asn', '.asn1']
  },
  'asp.net': {
    type: 'programming',
    extensions: ['.asax', '.ascx', '.ashx', '.asmx', '.aspx', '.axd'],
    aliases: ['aspx', 'aspx-vb']
  },
  aspectj: {
    type: 'programming',
    extensions: ['.aj']
  },
  assembly: {
    type: 'programming',
    extensions: ['.asm', '.a51', '.i', '.inc', '.nas', '.nasm', '.s'],
    aliases: ['asm', 'nasm']
  },
  astro: {
    type: 'markup',
    extensions: ['.astro']
  },
  asymptote: {
    type: 'programming',
    extensions: ['.asy']
  },
  ats: {
    type: 'programming',
    extensions: ['.dats', '.hats', '.sats'],
    aliases: ['ats2']
  },
  augeas: {
    type: 'programming',
    extensions: ['.aug']
  },
  autohotkey: {
    type: 'programming',
    extensions: ['.ahk', '.ahkl'],
    aliases: ['ahk']
  },
  autoit: {
    type: 'programming',
    extensions: ['.au3'],
    aliases: ['au3', 'AutoIt3', 'AutoItScript']
  },
  'avro idl': {
    type: 'data',
    extensions: ['.avdl']
  },
  awk: {
    type: 'programming',
    extensions: ['.awk', '.auk', '.gawk', '.mawk', '.nawk']
  },
  b4x: {
    type: 'programming',
    extensions: ['.bas'],
    aliases: ['basic for android']
  },
  ballerina: {
    type: 'programming',
    extensions: ['.bal']
  },
  basic: {
    type: 'programming',
    extensions: ['.bas']
  },
  batchfile: {
    type: 'programming',
    extensions: ['.bat', '.cmd'],
    aliases: ['bat', 'batch', 'dosbatch', 'winbatch']
  },
  beef: {
    type: 'programming',
    extensions: ['.bf']
  },
  befunge: {
    type: 'programming',
    extensions: ['.befunge', '.bf']
  },
  berry: {
    type: 'programming',
    extensions: ['.be'],
    aliases: ['be']
  },
  bibtex: {
    type: 'markup',
    extensions: ['.bib', '.bibtex']
  },
  'bibtex style': {
    type: 'programming',
    extensions: ['.bst']
  },
  bicep: {
    type: 'programming',
    extensions: ['.bicep', '.bicepparam']
  },
  bikeshed: {
    type: 'markup',
    extensions: ['.bs']
  },
  bison: {
    type: 'programming',
    extensions: ['.bison']
  },
  bitbake: {
    type: 'programming',
    extensions: ['.bb', '.bbappend', '.bbclass', '.inc']
  },
  blade: {
    type: 'markup',
    extensions: ['.blade', '.blade.php']
  },
  blitzbasic: {
    type: 'programming',
    extensions: ['.bb', '.decls'],
    aliases: ['b3d', 'blitz3d', 'blitzplus', 'bplus']
  },
  blitzmax: {
    type: 'programming',
    extensions: ['.bmx'],
    aliases: ['bmax']
  },
  bluespec: {
    type: 'programming',
    extensions: ['.bsv'],
    aliases: ['bluespec bsv', 'bsv']
  },
  'bluespec bh': {
    type: 'programming',
    extensions: ['.bs'],
    aliases: ['bh', 'bluespec classic']
  },
  boo: {
    type: 'programming',
    extensions: ['.boo']
  },
  boogie: {
    type: 'programming',
    extensions: ['.bpl']
  },
  bqn: {
    type: 'programming',
    extensions: ['.bqn']
  },
  brainfuck: {
    type: 'programming',
    extensions: ['.b', '.bf']
  },
  brighterscript: {
    type: 'programming',
    extensions: ['.bs']
  },
  brightscript: {
    type: 'programming',
    extensions: ['.brs']
  },
  buildstream: {
    type: 'data',
    extensions: ['.bst']
  },
  c: {
    type: 'programming',
    extensions: ['.c', '.cats', '.h', '.h.in', '.idc']
  },
  'c-objdump': {
    type: 'data',
    extensions: ['.c-objdump']
  },
  'c#': {
    type: 'programming',
    extensions: ['.cs', '.cake', '.cs.pp', '.csx', '.linq'],
    aliases: ['csharp', 'cake', 'cakescript']
  },
  'c++': {
    type: 'programming',
    extensions: [
      '.cpp',
      '.c++',
      '.cc',
      '.cp',
      '.cppm',
      '.cxx',
      '.h',
      '.h++',
      '.hh',
      '.hpp',
      '.hxx',
      '.inc',
      '.inl',
      '.ino',
      '.ipp',
      '.ixx',
      '.re',
      '.tcc',
      '.tpp',
      '.txx'
    ],
    aliases: ['cpp']
  },
  'c2hs haskell': {
    type: 'programming',
    extensions: ['.chs'],
    aliases: ['c2hs']
  },
  'cabal config': {
    type: 'data',
    extensions: ['.cabal'],
    aliases: ['Cabal']
  },
  caddyfile: {
    type: 'data',
    extensions: ['.caddyfile'],
    aliases: ['Caddy']
  },
  cadence: {
    type: 'programming',
    extensions: ['.cdc']
  },
  cairo: {
    type: 'programming',
    extensions: ['.cairo']
  },
  'cairo zero': {
    type: 'programming',
    extensions: ['.cairo']
  },
  cameligo: {
    type: 'programming',
    extensions: ['.mligo']
  },
  'cap cds': {
    type: 'programming',
    extensions: ['.cds'],
    aliases: ['cds']
  },
  "cap'n proto": {
    type: 'programming',
    extensions: ['.capnp']
  },
  carbon: {
    type: 'programming',
    extensions: ['.carbon']
  },
  cartocss: {
    type: 'programming',
    extensions: ['.mss'],
    aliases: ['Carto']
  },
  ceylon: {
    type: 'programming',
    extensions: ['.ceylon']
  },
  chapel: {
    type: 'programming',
    extensions: ['.chpl'],
    aliases: ['chpl']
  },
  charity: {
    type: 'programming',
    extensions: ['.ch']
  },
  checksums: {
    type: 'data',
    extensions: [
      '.crc32',
      '.md2',
      '.md4',
      '.md5',
      '.sha1',
      '.sha2',
      '.sha224',
      '.sha256',
      '.sha256sum',
      '.sha3',
      '.sha384',
      '.sha512'
    ],
    aliases: ['checksum', 'hash', 'hashes', 'sum', 'sums']
  },
  chuck: {
    type: 'programming',
    extensions: ['.ck']
  },
  cil: {
    type: 'data',
    extensions: ['.cil']
  },
  circom: {
    type: 'programming',
    extensions: ['.circom']
  },
  cirru: {
    type: 'programming',
    extensions: ['.cirru']
  },
  clarion: {
    type: 'programming',
    extensions: ['.clw']
  },
  clarity: {
    type: 'programming',
    extensions: ['.clar']
  },
  'classic asp': {
    type: 'programming',
    extensions: ['.asp'],
    aliases: ['asp']
  },
  clean: {
    type: 'programming',
    extensions: ['.icl', '.dcl']
  },
  click: {
    type: 'programming',
    extensions: ['.click']
  },
  clips: {
    type: 'programming',
    extensions: ['.clp']
  },
  clojure: {
    type: 'programming',
    extensions: ['.clj', '.bb', '.boot', '.cl2', '.cljc', '.cljs', '.cljs.hl', '.cljscm', '.cljx', '.hic']
  },
  'closure templates': {
    type: 'markup',
    extensions: ['.soy'],
    aliases: ['soy']
  },
  clue: {
    type: 'programming',
    extensions: ['.clue']
  },
  cmake: {
    type: 'programming',
    extensions: ['.cmake', '.cmake.in']
  },
  cobol: {
    type: 'programming',
    extensions: ['.cob', '.cbl', '.ccp', '.cobol', '.cpy']
  },
  codeql: {
    type: 'programming',
    extensions: ['.ql', '.qll'],
    aliases: ['ql']
  },
  coffeescript: {
    type: 'programming',
    extensions: ['.coffee', '._coffee', '.cake', '.cjsx', '.iced'],
    aliases: ['coffee', 'coffee-script']
  },
  coldfusion: {
    type: 'programming',
    extensions: ['.cfm', '.cfml'],
    aliases: ['cfm', 'cfml', 'coldfusion html']
  },
  'coldfusion cfc': {
    type: 'programming',
    extensions: ['.cfc'],
    aliases: ['cfc']
  },
  collada: {
    type: 'data',
    extensions: ['.dae']
  },
  'common lisp': {
    type: 'programming',
    extensions: ['.lisp', '.asd', '.cl', '.l', '.lsp', '.ny', '.podsl', '.sexp'],
    aliases: ['lisp']
  },
  'common workflow language': {
    type: 'programming',
    extensions: ['.cwl'],
    aliases: ['cwl']
  },
  'component pascal': {
    type: 'programming',
    extensions: ['.cp', '.cps']
  },
  'conll-u': {
    type: 'data',
    extensions: ['.conllu', '.conll'],
    aliases: ['CoNLL', 'CoNLL-X']
  },
  cool: {
    type: 'programming',
    extensions: ['.cl']
  },
  'cpp-objdump': {
    type: 'data',
    extensions: ['.cppobjdump', '.c++-objdump', '.c++objdump', '.cpp-objdump', '.cxx-objdump'],
    aliases: ['c++-objdump']
  },
  creole: {
    type: 'prose',
    extensions: ['.creole']
  },
  crontab: {
    type: 'data',
    aliases: ['cron', 'cron table']
  },
  crystal: {
    type: 'programming',
    extensions: ['.cr']
  },
  cson: {
    type: 'data',
    extensions: ['.cson']
  },
  csound: {
    type: 'programming',
    extensions: ['.orc', '.udo'],
    aliases: ['csound-orc']
  },
  'csound document': {
    type: 'programming',
    extensions: ['.csd'],
    aliases: ['csound-csd']
  },
  'csound score': {
    type: 'programming',
    extensions: ['.sco'],
    aliases: ['csound-sco']
  },
  css: {
    type: 'markup',
    extensions: ['.css']
  },
  csv: {
    type: 'data',
    extensions: ['.csv']
  },
  cuda: {
    type: 'programming',
    extensions: ['.cu', '.cuh']
  },
  cue: {
    type: 'programming',
    extensions: ['.cue']
  },
  'cue sheet': {
    type: 'data',
    extensions: ['.cue']
  },
  'curl config': {
    type: 'data',
    aliases: ['curlrc']
  },
  curry: {
    type: 'programming',
    extensions: ['.curry']
  },
  cweb: {
    type: 'programming',
    extensions: ['.w']
  },
  cycript: {
    type: 'programming',
    extensions: ['.cy']
  },
  cylc: {
    type: 'data',
    extensions: ['.cylc']
  },
  cypher: {
    type: 'programming',
    extensions: ['.cyp', '.cypher']
  },
  cython: {
    type: 'programming',
    extensions: ['.pyx', '.pxd', '.pxi'],
    aliases: ['pyrex']
  },
  d: {
    type: 'programming',
    extensions: ['.d', '.di'],
    aliases: ['Dlang']
  },
  'd-objdump': {
    type: 'data',
    extensions: ['.d-objdump']
  },
  d2: {
    type: 'markup',
    extensions: ['.d2'],
    aliases: ['d2lang']
  },
  dafny: {
    type: 'programming',
    extensions: ['.dfy']
  },
  'darcs patch': {
    type: 'data',
    extensions: ['.darcspatch', '.dpatch'],
    aliases: ['dpatch']
  },
  dart: {
    type: 'programming',
    extensions: ['.dart']
  },
  daslang: {
    type: 'programming',
    extensions: ['.das']
  },
  dataweave: {
    type: 'programming',
    extensions: ['.dwl']
  },
  'debian package control file': {
    type: 'data',
    extensions: ['.dsc']
  },
  denizenscript: {
    type: 'programming',
    extensions: ['.dsc']
  },
  desktop: {
    type: 'data',
    extensions: ['.desktop', '.desktop.in', '.service']
  },
  dhall: {
    type: 'programming',
    extensions: ['.dhall']
  },
  diff: {
    type: 'data',
    extensions: ['.diff', '.patch'],
    aliases: ['udiff']
  },
  'digital command language': {
    type: 'programming',
    extensions: ['.com'],
    aliases: ['dcl']
  },
  dircolors: {
    type: 'data',
    extensions: ['.dircolors']
  },
  'directx 3d file': {
    type: 'data',
    extensions: ['.x']
  },
  dm: {
    type: 'programming',
    extensions: ['.dm'],
    aliases: ['byond']
  },
  'dns zone': {
    type: 'data',
    extensions: ['.zone', '.arpa']
  },
  dockerfile: {
    type: 'programming',
    extensions: ['.dockerfile', '.containerfile'],
    aliases: ['Containerfile']
  },
  dogescript: {
    type: 'programming',
    extensions: ['.djs']
  },
  dotenv: {
    type: 'data',
    extensions: ['.env']
  },
  dtrace: {
    type: 'programming',
    extensions: ['.d'],
    aliases: ['dtrace-script']
  },
  dylan: {
    type: 'programming',
    extensions: ['.dylan', '.dyl', '.intr', '.lid']
  },
  e: {
    type: 'programming',
    extensions: ['.e']
  },
  'e-mail': {
    type: 'data',
    extensions: ['.eml', '.mbox'],
    aliases: ['email', 'eml', 'mail', 'mbox']
  },
  eagle: {
    type: 'data',
    extensions: ['.sch', '.brd']
  },
  earthly: {
    type: 'programming',
    aliases: ['Earthfile']
  },
  easybuild: {
    type: 'data',
    extensions: ['.eb']
  },
  ebnf: {
    type: 'data',
    extensions: ['.ebnf']
  },
  ec: {
    type: 'programming',
    extensions: ['.ec', '.eh']
  },
  'ecere projects': {
    type: 'data',
    extensions: ['.epj']
  },
  ecl: {
    type: 'programming',
    extensions: ['.ecl', '.eclxml']
  },
  eclipse: {
    type: 'programming',
    extensions: ['.ecl']
  },
  ecmarkup: {
    type: 'markup',
    extensions: ['.html'],
    aliases: ['ecmarkdown']
  },
  edge: {
    type: 'markup',
    extensions: ['.edge']
  },
  edgeql: {
    type: 'programming',
    extensions: ['.edgeql', '.esdl'],
    aliases: ['esdl']
  },
  editorconfig: {
    type: 'data',
    extensions: ['.editorconfig'],
    aliases: ['editor-config']
  },
  'edje data collection': {
    type: 'data',
    extensions: ['.edc']
  },
  edn: {
    type: 'data',
    extensions: ['.edn']
  },
  eiffel: {
    type: 'programming',
    extensions: ['.e']
  },
  ejs: {
    type: 'markup',
    extensions: ['.ejs', '.ect', '.ejs.t', '.jst']
  },
  elixir: {
    type: 'programming',
    extensions: ['.ex', '.exs']
  },
  elm: {
    type: 'programming',
    extensions: ['.elm']
  },
  elvish: {
    type: 'programming',
    extensions: ['.elv']
  },
  'emacs lisp': {
    type: 'programming',
    extensions: ['.el', '.emacs', '.emacs.desktop'],
    aliases: ['elisp', 'emacs']
  },
  emberscript: {
    type: 'programming',
    extensions: ['.em', '.emberscript']
  },
  eq: {
    type: 'programming',
    extensions: ['.eq']
  },
  erlang: {
    type: 'programming',
    extensions: ['.erl', '.app', '.app.src', '.es', '.escript', '.hrl', '.xrl', '.yrl']
  },
  euphoria: {
    type: 'programming',
    extensions: ['.e', '.ex']
  },
  'f*': {
    type: 'programming',
    extensions: ['.fst', '.fsti'],
    aliases: ['fstar']
  },
  'f#': {
    type: 'programming',
    extensions: ['.fs', '.fsi', '.fsx'],
    aliases: ['fsharp']
  },
  factor: {
    type: 'programming',
    extensions: ['.factor']
  },
  fancy: {
    type: 'programming',
    extensions: ['.fy', '.fancypack']
  },
  fantom: {
    type: 'programming',
    extensions: ['.fan']
  },
  faust: {
    type: 'programming',
    extensions: ['.dsp']
  },
  fennel: {
    type: 'programming',
    extensions: ['.fnl']
  },
  'figlet font': {
    type: 'data',
    extensions: ['.flf'],
    aliases: ['FIGfont']
  },
  'filebench wml': {
    type: 'programming',
    extensions: ['.f']
  },
  filterscript: {
    type: 'programming',
    extensions: ['.fs']
  },
  firrtl: {
    type: 'programming',
    extensions: ['.fir']
  },
  fish: {
    type: 'programming',
    extensions: ['.fish']
  },
  fluent: {
    type: 'programming',
    extensions: ['.ftl']
  },
  flux: {
    type: 'programming',
    extensions: ['.fx', '.flux']
  },
  formatted: {
    type: 'data',
    extensions: ['.for', '.eam.fs']
  },
  forth: {
    type: 'programming',
    extensions: ['.fth', '.4th', '.f', '.for', '.forth', '.fr', '.frt', '.fs']
  },
  fortran: {
    type: 'programming',
    extensions: ['.f', '.f77', '.for', '.fpp']
  },
  'fortran free form': {
    type: 'programming',
    extensions: ['.f90', '.f03', '.f08', '.f95']
  },
  freebasic: {
    type: 'programming',
    extensions: ['.bi', '.bas'],
    aliases: ['fb']
  },
  freemarker: {
    type: 'programming',
    extensions: ['.ftl'],
    aliases: ['ftl']
  },
  frege: {
    type: 'programming',
    extensions: ['.fr']
  },
  futhark: {
    type: 'programming',
    extensions: ['.fut']
  },
  'g-code': {
    type: 'programming',
    extensions: ['.g', '.cnc', '.gco', '.gcode']
  },
  'game maker language': {
    type: 'programming',
    extensions: ['.gml']
  },
  gaml: {
    type: 'programming',
    extensions: ['.gaml']
  },
  gams: {
    type: 'programming',
    extensions: ['.gms']
  },
  gap: {
    type: 'programming',
    extensions: ['.g', '.gap', '.gd', '.gi', '.tst']
  },
  'gcc machine description': {
    type: 'programming',
    extensions: ['.md']
  },
  gdb: {
    type: 'programming',
    extensions: ['.gdb', '.gdbinit']
  },
  gdscript: {
    type: 'programming',
    extensions: ['.gd']
  },
  gdshader: {
    type: 'programming',
    extensions: ['.gdshader', '.gdshaderinc']
  },
  gedcom: {
    type: 'data',
    extensions: ['.ged']
  },
  gemini: {
    type: 'prose',
    extensions: ['.gmi'],
    aliases: ['gemtext']
  },
  'genero 4gl': {
    type: 'programming',
    extensions: ['.4gl']
  },
  'genero per': {
    type: 'markup',
    extensions: ['.per']
  },
  genie: {
    type: 'programming',
    extensions: ['.gs']
  },
  genshi: {
    type: 'programming',
    extensions: ['.kid'],
    aliases: ['xml+genshi', 'xml+kid']
  },
  'gentoo ebuild': {
    type: 'programming',
    extensions: ['.ebuild']
  },
  'gentoo eclass': {
    type: 'programming',
    extensions: ['.eclass']
  },
  'gerber image': {
    type: 'data',
    extensions: [
      '.gbr',
      '.cmp',
      '.gbl',
      '.gbo',
      '.gbp',
      '.gbs',
      '.gko',
      '.gml',
      '.gpb',
      '.gpt',
      '.gtl',
      '.gto',
      '.gtp',
      '.gts',
      '.ncl',
      '.sol'
    ],
    aliases: ['rs-274x']
  },
  'gettext catalog': {
    type: 'prose',
    extensions: ['.po', '.pot'],
    aliases: ['pot']
  },
  gherkin: {
    type: 'programming',
    extensions: ['.feature', '.story'],
    aliases: ['cucumber']
  },
  'git attributes': {
    type: 'data',
    aliases: ['gitattributes']
  },
  'git config': {
    type: 'data',
    extensions: ['.gitconfig'],
    aliases: ['gitconfig', 'gitmodules']
  },
  'git revision list': {
    type: 'data',
    aliases: ['Git Blame Ignore Revs']
  },
  gleam: {
    type: 'programming',
    extensions: ['.gleam']
  },
  'glimmer js': {
    type: 'programming',
    extensions: ['.gjs']
  },
  'glimmer ts': {
    type: 'programming',
    extensions: ['.gts']
  },
  glsl: {
    type: 'programming',
    extensions: [
      '.glsl',
      '.fp',
      '.frag',
      '.frg',
      '.fs',
      '.fsh',
      '.fshader',
      '.geo',
      '.geom',
      '.glslf',
      '.glslv',
      '.gs',
      '.gshader',
      '.rchit',
      '.rmiss',
      '.shader',
      '.tesc',
      '.tese',
      '.vert',
      '.vrx',
      '.vs',
      '.vsh',
      '.vshader'
    ]
  },
  glyph: {
    type: 'programming',
    extensions: ['.glf']
  },
  'glyph bitmap distribution format': {
    type: 'data',
    extensions: ['.bdf']
  },
  gn: {
    type: 'data',
    extensions: ['.gn', '.gni']
  },
  gnuplot: {
    type: 'programming',
    extensions: ['.gp', '.gnu', '.gnuplot', '.p', '.plot', '.plt']
  },
  go: {
    type: 'programming',
    extensions: ['.go'],
    aliases: ['golang']
  },
  'go checksums': {
    type: 'data',
    aliases: ['go.sum', 'go sum', 'go.work.sum', 'go work sum']
  },
  'go module': {
    type: 'data',
    aliases: ['go.mod', 'go mod']
  },
  'go workspace': {
    type: 'data',
    aliases: ['go.work', 'go work']
  },
  'godot resource': {
    type: 'data',
    extensions: ['.gdnlib', '.gdns', '.tres', '.tscn']
  },
  golo: {
    type: 'programming',
    extensions: ['.golo']
  },
  gosu: {
    type: 'programming',
    extensions: ['.gs', '.gst', '.gsx', '.vark']
  },
  grace: {
    type: 'programming',
    extensions: ['.grace']
  },
  gradle: {
    type: 'data',
    extensions: ['.gradle']
  },
  'gradle kotlin dsl': {
    type: 'data',
    extensions: ['.gradle.kts']
  },
  'grammatical framework': {
    type: 'programming',
    extensions: ['.gf'],
    aliases: ['gf']
  },
  'graph modeling language': {
    type: 'data',
    extensions: ['.gml']
  },
  graphql: {
    type: 'data',
    extensions: ['.graphql', '.gql', '.graphqls']
  },
  'graphviz (dot)': {
    type: 'data',
    extensions: ['.dot', '.gv']
  },
  groovy: {
    type: 'programming',
    extensions: ['.groovy', '.grt', '.gtpl', '.gvy']
  },
  'groovy server pages': {
    type: 'programming',
    extensions: ['.gsp'],
    aliases: ['gsp', 'java server page']
  },
  gsc: {
    type: 'programming',
    extensions: ['.gsc', '.csc', '.gsh']
  },
  hack: {
    type: 'programming',
    extensions: ['.hack', '.hh', '.hhi', '.php']
  },
  haml: {
    type: 'markup',
    extensions: ['.haml', '.haml.deface']
  },
  handlebars: {
    type: 'markup',
    extensions: ['.handlebars', '.hbs'],
    aliases: ['hbs', 'htmlbars']
  },
  haproxy: {
    type: 'data',
    extensions: ['.cfg']
  },
  harbour: {
    type: 'programming',
    extensions: ['.hb']
  },
  hare: {
    type: 'programming',
    extensions: ['.ha']
  },
  haskell: {
    type: 'programming',
    extensions: ['.hs', '.hs-boot', '.hsc']
  },
  haxe: {
    type: 'programming',
    extensions: ['.hx', '.hxsl']
  },
  hcl: {
    type: 'programming',
    extensions: ['.hcl', '.nomad', '.tf', '.tfvars', '.workflow'],
    aliases: ['HashiCorp Configuration Language', 'terraform']
  },
  hip: {
    type: 'programming',
    extensions: ['.hip']
  },
  hiveql: {
    type: 'programming',
    extensions: ['.q', '.hql']
  },
  hlsl: {
    type: 'programming',
    extensions: ['.hlsl', '.cginc', '.fx', '.fxh', '.hlsli']
  },
  hocon: {
    type: 'data',
    extensions: ['.hocon']
  },
  holyc: {
    type: 'programming',
    extensions: ['.hc']
  },
  hoon: {
    type: 'programming',
    extensions: ['.hoon']
  },
  'hosts file': {
    type: 'data',
    aliases: ['hosts']
  },
  html: {
    type: 'markup',
    extensions: ['.html', '.hta', '.htm', '.html.hl', '.inc', '.xht', '.xhtml'],
    aliases: ['xhtml']
  },
  'html+ecr': {
    type: 'markup',
    extensions: ['.ecr'],
    aliases: ['ecr']
  },
  'html+eex': {
    type: 'markup',
    extensions: ['.html.eex', '.heex', '.leex'],
    aliases: ['eex', 'heex', 'leex']
  },
  'html+erb': {
    type: 'markup',
    extensions: ['.erb', '.erb.deface', '.rhtml'],
    aliases: ['erb', 'rhtml', 'html+ruby']
  },
  'html+php': {
    type: 'markup',
    extensions: ['.phtml']
  },
  'html+razor': {
    type: 'markup',
    extensions: ['.cshtml', '.razor'],
    aliases: ['razor']
  },
  http: {
    type: 'data',
    extensions: ['.http']
  },
  hxml: {
    type: 'data',
    extensions: ['.hxml']
  },
  hy: {
    type: 'programming',
    extensions: ['.hy'],
    aliases: ['hylang']
  },
  hyphy: {
    type: 'programming',
    extensions: ['.bf']
  },
  icalendar: {
    type: 'data',
    extensions: ['.ics', '.ical'],
    aliases: ['iCal']
  },
  idl: {
    type: 'programming',
    extensions: ['.pro', '.dlm']
  },
  idris: {
    type: 'programming',
    extensions: ['.idr', '.lidr']
  },
  'ignore list': {
    type: 'data',
    extensions: ['.gitignore'],
    aliases: ['ignore', 'gitignore', 'git-ignore']
  },
  'igor pro': {
    type: 'programming',
    extensions: ['.ipf'],
    aliases: ['igor', 'igorpro']
  },
  'imagej macro': {
    type: 'programming',
    extensions: ['.ijm'],
    aliases: ['ijm']
  },
  imba: {
    type: 'programming',
    extensions: ['.imba']
  },
  'inform 7': {
    type: 'programming',
    extensions: ['.ni', '.i7x'],
    aliases: ['i7', 'inform7']
  },
  ini: {
    type: 'data',
    extensions: ['.ini', '.cfg', '.cnf', '.dof', '.frm', '.lektorproject', '.prefs', '.pro', '.properties', '.url'],
    aliases: ['dosini']
  },
  ink: {
    type: 'programming',
    extensions: ['.ink']
  },
  'inno setup': {
    type: 'programming',
    extensions: ['.iss', '.isl']
  },
  io: {
    type: 'programming',
    extensions: ['.io']
  },
  ioke: {
    type: 'programming',
    extensions: ['.ik']
  },
  'irc log': {
    type: 'data',
    extensions: ['.irclog', '.weechatlog'],
    aliases: ['irc', 'irc logs']
  },
  isabelle: {
    type: 'programming',
    extensions: ['.thy']
  },
  ispc: {
    type: 'programming',
    extensions: ['.ispc']
  },
  j: {
    type: 'programming',
    extensions: ['.ijs']
  },
  jai: {
    type: 'programming',
    extensions: ['.jai']
  },
  janet: {
    type: 'programming',
    extensions: ['.janet']
  },
  jasmin: {
    type: 'programming',
    extensions: ['.j']
  },
  java: {
    type: 'programming',
    extensions: ['.java', '.jav', '.jsh']
  },
  'java properties': {
    type: 'data',
    extensions: ['.properties']
  },
  'java server pages': {
    type: 'programming',
    extensions: ['.jsp', '.tag'],
    aliases: ['jsp']
  },
  'java template engine': {
    type: 'programming',
    extensions: ['.jte'],
    aliases: ['jte']
  },
  javascript: {
    type: 'programming',
    extensions: [
      '.js',
      '._js',
      '.bones',
      '.cjs',
      '.es',
      '.es6',
      '.frag',
      '.gs',
      '.jake',
      '.javascript',
      '.jsb',
      '.jscad',
      '.jsfl',
      '.jslib',
      '.jsm',
      '.jspre',
      '.jss',
      '.jsx',
      '.mjs',
      '.njs',
      '.pac',
      '.sjs',
      '.ssjs',
      '.xsjs',
      '.xsjslib'
    ],
    aliases: ['js', 'node']
  },
  'javascript+erb': {
    type: 'programming',
    extensions: ['.js.erb']
  },
  jcl: {
    type: 'programming',
    extensions: ['.jcl']
  },
  'jest snapshot': {
    type: 'data',
    extensions: ['.snap']
  },
  'jetbrains mps': {
    type: 'programming',
    extensions: ['.mps', '.mpl', '.msd'],
    aliases: ['mps']
  },
  jflex: {
    type: 'programming',
    extensions: ['.flex', '.jflex']
  },
  jinja: {
    type: 'markup',
    extensions: ['.jinja', '.j2', '.jinja2'],
    aliases: ['django', 'html+django', 'html+jinja', 'htmldjango']
  },
  jison: {
    type: 'programming',
    extensions: ['.jison']
  },
  'jison lex': {
    type: 'programming',
    extensions: ['.jisonlex']
  },
  jolie: {
    type: 'programming',
    extensions: ['.ol', '.iol']
  },
  jq: {
    type: 'programming',
    extensions: ['.jq']
  },
  json: {
    type: 'data',
    extensions: [
      '.json',
      '.4DForm',
      '.4DProject',
      '.avsc',
      '.geojson',
      '.gltf',
      '.har',
      '.ice',
      '.JSON-tmLanguage',
      '.json.example',
      '.jsonl',
      '.mcmeta',
      '.sarif',
      '.tact',
      '.tfstate',
      '.tfstate.backup',
      '.topojson',
      '.webapp',
      '.webmanifest',
      '.yy',
      '.yyp'
    ],
    aliases: ['geojson', 'jsonl', 'sarif', 'topojson']
  },
  'json with comments': {
    type: 'data',
    extensions: [
      '.jsonc',
      '.code-snippets',
      '.code-workspace',
      '.sublime-build',
      '.sublime-color-scheme',
      '.sublime-commands',
      '.sublime-completions',
      '.sublime-keymap',
      '.sublime-macro',
      '.sublime-menu',
      '.sublime-mousemap',
      '.sublime-project',
      '.sublime-settings',
      '.sublime-theme',
      '.sublime-workspace',
      '.sublime_metrics',
      '.sublime_session'
    ],
    aliases: ['jsonc']
  },
  json5: {
    type: 'data',
    extensions: ['.json5']
  },
  jsoniq: {
    type: 'programming',
    extensions: ['.jq']
  },
  jsonld: {
    type: 'data',
    extensions: ['.jsonld']
  },
  jsonnet: {
    type: 'programming',
    extensions: ['.jsonnet', '.libsonnet']
  },
  julia: {
    type: 'programming',
    extensions: ['.jl']
  },
  'jupyter notebook': {
    type: 'markup',
    extensions: ['.ipynb'],
    aliases: ['IPython Notebook']
  },
  just: {
    type: 'programming',
    extensions: ['.just'],
    aliases: ['Justfile']
  },
  'kaitai struct': {
    type: 'programming',
    extensions: ['.ksy'],
    aliases: ['ksy']
  },
  kakounescript: {
    type: 'programming',
    extensions: ['.kak'],
    aliases: ['kak', 'kakscript']
  },
  kdl: {
    type: 'data',
    extensions: ['.kdl']
  },
  kerboscript: {
    type: 'programming',
    extensions: ['.ks']
  },
  'kicad layout': {
    type: 'data',
    extensions: ['.kicad_pcb', '.kicad_mod', '.kicad_wks'],
    aliases: ['pcbnew']
  },
  'kicad legacy layout': {
    type: 'data',
    extensions: ['.brd']
  },
  'kicad schematic': {
    type: 'data',
    extensions: ['.kicad_sch', '.kicad_sym', '.sch'],
    aliases: ['eeschema schematic']
  },
  kickstart: {
    type: 'data',
    extensions: ['.ks']
  },
  kit: {
    type: 'markup',
    extensions: ['.kit']
  },
  koka: {
    type: 'programming',
    extensions: ['.kk']
  },
  kotlin: {
    type: 'programming',
    extensions: ['.kt', '.ktm', '.kts']
  },
  krl: {
    type: 'programming',
    extensions: ['.krl']
  },
  kusto: {
    type: 'data',
    extensions: ['.csl', '.kql']
  },
  kvlang: {
    type: 'markup',
    extensions: ['.kv']
  },
  labview: {
    type: 'programming',
    extensions: ['.lvproj', '.lvclass', '.lvlib']
  },
  lark: {
    type: 'data',
    extensions: ['.lark']
  },
  lasso: {
    type: 'programming',
    extensions: ['.lasso', '.las', '.lasso8', '.lasso9'],
    aliases: ['lassoscript']
  },
  latte: {
    type: 'markup',
    extensions: ['.latte']
  },
  lean: {
    type: 'programming',
    extensions: ['.lean', '.hlean']
  },
  'lean 4': {
    type: 'programming',
    extensions: ['.lean']
  },
  leo: {
    type: 'programming',
    extensions: ['.leo']
  },
  less: {
    type: 'markup',
    extensions: ['.less'],
    aliases: ['less-css']
  },
  lex: {
    type: 'programming',
    extensions: ['.l', '.lex'],
    aliases: ['flex']
  },
  lfe: {
    type: 'programming',
    extensions: ['.lfe']
  },
  ligolang: {
    type: 'programming',
    extensions: ['.ligo']
  },
  lilypond: {
    type: 'programming',
    extensions: ['.ly', '.ily']
  },
  limbo: {
    type: 'programming',
    extensions: ['.b', '.m']
  },
  'linear programming': {
    type: 'programming',
    extensions: ['.lp']
  },
  'linker script': {
    type: 'programming',
    extensions: ['.ld', '.lds', '.x']
  },
  'linux kernel module': {
    type: 'data',
    extensions: ['.mod']
  },
  liquid: {
    type: 'markup',
    extensions: ['.liquid']
  },
  'literate agda': {
    type: 'programming',
    extensions: ['.lagda']
  },
  'literate coffeescript': {
    type: 'programming',
    extensions: ['.litcoffee', '.coffee.md'],
    aliases: ['litcoffee']
  },
  'literate haskell': {
    type: 'programming',
    extensions: ['.lhs'],
    aliases: ['lhaskell', 'lhs']
  },
  'livecode script': {
    type: 'programming',
    extensions: ['.livecodescript']
  },
  livescript: {
    type: 'programming',
    extensions: ['.ls', '._ls'],
    aliases: ['live-script', 'ls']
  },
  llvm: {
    type: 'programming',
    extensions: ['.ll']
  },
  logos: {
    type: 'programming',
    extensions: ['.xm', '.x', '.xi']
  },
  logtalk: {
    type: 'programming',
    extensions: ['.lgt', '.logtalk']
  },
  lolcode: {
    type: 'programming',
    extensions: ['.lol']
  },
  lookml: {
    type: 'programming',
    extensions: ['.lkml', '.lookml']
  },
  loomscript: {
    type: 'programming',
    extensions: ['.ls']
  },
  lsl: {
    type: 'programming',
    extensions: ['.lsl', '.lslp']
  },
  'ltspice symbol': {
    type: 'data',
    extensions: ['.asy']
  },
  lua: {
    type: 'programming',
    extensions: ['.lua', '.fcgi', '.nse', '.p8', '.pd_lua', '.rbxs', '.rockspec', '.wlua']
  },
  luau: {
    type: 'programming',
    extensions: ['.luau']
  },
  m: {
    type: 'programming',
    extensions: ['.mumps', '.m'],
    aliases: ['mumps']
  },
  m3u: {
    type: 'data',
    extensions: ['.m3u', '.m3u8'],
    aliases: ['hls playlist', 'm3u playlist']
  },
  m4: {
    type: 'programming',
    extensions: ['.m4', '.mc']
  },
  m4sugar: {
    type: 'programming',
    extensions: ['.m4'],
    aliases: ['autoconf']
  },
  macaulay2: {
    type: 'programming',
    extensions: ['.m2'],
    aliases: ['m2']
  },
  makefile: {
    type: 'programming',
    extensions: ['.mak', '.d', '.make', '.makefile', '.mk', '.mkfile'],
    aliases: ['bsdmake', 'make', 'mf']
  },
  mako: {
    type: 'programming',
    extensions: ['.mako', '.mao']
  },
  markdown: {
    type: 'prose',
    extensions: [
      '.md',
      '.livemd',
      '.markdown',
      '.mdown',
      '.mdwn',
      '.mkd',
      '.mkdn',
      '.mkdown',
      '.ronn',
      '.scd',
      '.workbook'
    ],
    aliases: ['md', 'pandoc']
  },
  marko: {
    type: 'markup',
    extensions: ['.marko'],
    aliases: ['markojs']
  },
  mask: {
    type: 'markup',
    extensions: ['.mask']
  },
  mathematica: {
    type: 'programming',
    extensions: ['.mathematica', '.cdf', '.m', '.ma', '.mt', '.nb', '.nbp', '.wl', '.wlt'],
    aliases: ['mma', 'wolfram', 'wolfram language', 'wolfram lang', 'wl']
  },
  matlab: {
    type: 'programming',
    extensions: ['.matlab', '.m'],
    aliases: ['octave']
  },
  max: {
    type: 'programming',
    extensions: ['.maxpat', '.maxhelp', '.maxproj', '.mxt', '.pat'],
    aliases: ['max/msp', 'maxmsp']
  },
  maxscript: {
    type: 'programming',
    extensions: ['.ms', '.mcr']
  },
  mcfunction: {
    type: 'programming',
    extensions: ['.mcfunction']
  },
  mdsvex: {
    type: 'markup',
    extensions: ['.svx']
  },
  mdx: {
    type: 'markup',
    extensions: ['.mdx']
  },
  mercury: {
    type: 'programming',
    extensions: ['.m', '.moo']
  },
  mermaid: {
    type: 'markup',
    extensions: ['.mmd', '.mermaid'],
    aliases: ['mermaid example']
  },
  metal: {
    type: 'programming',
    extensions: ['.metal']
  },
  'microsoft developer studio project': {
    type: 'data',
    extensions: ['.dsp']
  },
  'microsoft visual studio solution': {
    type: 'data',
    extensions: ['.sln']
  },
  minid: {
    type: 'programming',
    extensions: ['.minid']
  },
  miniyaml: {
    type: 'data',
    extensions: ['.yaml', '.yml']
  },
  minizinc: {
    type: 'programming',
    extensions: ['.mzn']
  },
  'minizinc data': {
    type: 'data',
    extensions: ['.dzn']
  },
  mint: {
    type: 'programming',
    extensions: ['.mint']
  },
  mirah: {
    type: 'programming',
    extensions: ['.druby', '.duby', '.mirah']
  },
  'mirc script': {
    type: 'programming',
    extensions: ['.mrc']
  },
  mlir: {
    type: 'programming',
    extensions: ['.mlir']
  },
  modelica: {
    type: 'programming',
    extensions: ['.mo']
  },
  'modula-2': {
    type: 'programming',
    extensions: ['.mod']
  },
  'modula-3': {
    type: 'programming',
    extensions: ['.i3', '.ig', '.m3', '.mg']
  },
  'module management system': {
    type: 'programming',
    extensions: ['.mms', '.mmk']
  },
  mojo: {
    type: 'programming',
    extensions: ['.mojo']
  },
  monkey: {
    type: 'programming',
    extensions: ['.monkey', '.monkey2']
  },
  'monkey c': {
    type: 'programming',
    extensions: ['.mc']
  },
  moocode: {
    type: 'programming',
    extensions: ['.moo']
  },
  moonbit: {
    type: 'programming',
    extensions: ['.mbt']
  },
  moonscript: {
    type: 'programming',
    extensions: ['.moon']
  },
  motoko: {
    type: 'programming',
    extensions: ['.mo']
  },
  'motorola 68k assembly': {
    type: 'programming',
    extensions: ['.asm', '.i', '.inc', '.s', '.x68'],
    aliases: ['m68k']
  },
  move: {
    type: 'programming',
    extensions: ['.move']
  },
  mql4: {
    type: 'programming',
    extensions: ['.mq4', '.mqh']
  },
  mql5: {
    type: 'programming',
    extensions: ['.mq5', '.mqh']
  },
  mtml: {
    type: 'markup',
    extensions: ['.mtml']
  },
  muf: {
    type: 'programming',
    extensions: ['.muf', '.m']
  },
  mupad: {
    type: 'programming',
    extensions: ['.mu']
  },
  muse: {
    type: 'prose',
    extensions: ['.muse'],
    aliases: ['amusewiki', 'emacs muse']
  },
  mustache: {
    type: 'markup',
    extensions: ['.mustache']
  },
  myghty: {
    type: 'programming',
    extensions: ['.myt']
  },
  nanorc: {
    type: 'data',
    extensions: ['.nanorc']
  },
  nasal: {
    type: 'programming',
    extensions: ['.nas']
  },
  nasl: {
    type: 'programming',
    extensions: ['.nasl', '.inc']
  },
  ncl: {
    type: 'programming',
    extensions: ['.ncl']
  },
  nearley: {
    type: 'programming',
    extensions: ['.ne', '.nearley']
  },
  nemerle: {
    type: 'programming',
    extensions: ['.n']
  },
  neon: {
    type: 'data',
    extensions: ['.neon'],
    aliases: ['nette object notation', 'ne-on']
  },
  nesc: {
    type: 'programming',
    extensions: ['.nc']
  },
  netlinx: {
    type: 'programming',
    extensions: ['.axs', '.axi']
  },
  'netlinx+erb': {
    type: 'programming',
    extensions: ['.axs.erb', '.axi.erb']
  },
  netlogo: {
    type: 'programming',
    extensions: ['.nlogo']
  },
  newlisp: {
    type: 'programming',
    extensions: ['.nl', '.lisp', '.lsp']
  },
  nextflow: {
    type: 'programming',
    extensions: ['.nf']
  },
  nginx: {
    type: 'data',
    extensions: ['.nginx', '.nginxconf', '.vhost'],
    aliases: ['nginx configuration file']
  },
  nim: {
    type: 'programming',
    extensions: ['.nim', '.nim.cfg', '.nimble', '.nimrod', '.nims']
  },
  ninja: {
    type: 'data',
    extensions: ['.ninja']
  },
  nit: {
    type: 'programming',
    extensions: ['.nit']
  },
  nix: {
    type: 'programming',
    extensions: ['.nix'],
    aliases: ['nixos']
  },
  nl: {
    type: 'data',
    extensions: ['.nl']
  },
  nmodl: {
    type: 'programming',
    extensions: ['.mod']
  },
  noir: {
    type: 'programming',
    extensions: ['.nr'],
    aliases: ['nargo']
  },
  'npm config': {
    type: 'data',
    aliases: ['npmrc']
  },
  nsis: {
    type: 'programming',
    extensions: ['.nsi', '.nsh']
  },
  nu: {
    type: 'programming',
    extensions: ['.nu'],
    aliases: ['nush']
  },
  numpy: {
    type: 'programming',
    extensions: ['.numpy', '.numpyw', '.numsc']
  },
  nunjucks: {
    type: 'markup',
    extensions: ['.njk'],
    aliases: ['njk']
  },
  nushell: {
    type: 'programming',
    extensions: ['.nu'],
    aliases: ['nu-script', 'nushell-script']
  },
  nwscript: {
    type: 'programming',
    extensions: ['.nss']
  },
  'oasv2-json': {
    type: 'data',
    extensions: ['.json']
  },
  'oasv2-yaml': {
    type: 'data',
    extensions: ['.yaml', '.yml']
  },
  'oasv3-json': {
    type: 'data',
    extensions: ['.json']
  },
  'oasv3-yaml': {
    type: 'data',
    extensions: ['.yaml', '.yml']
  },
  oberon: {
    type: 'programming',
    extensions: ['.ob2']
  },
  objdump: {
    type: 'data',
    extensions: ['.objdump']
  },
  'object data instance notation': {
    type: 'data',
    extensions: ['.odin']
  },
  'objective-c': {
    type: 'programming',
    extensions: ['.m', '.h'],
    aliases: ['obj-c', 'objc', 'objectivec']
  },
  'objective-c++': {
    type: 'programming',
    extensions: ['.mm'],
    aliases: ['obj-c++', 'objc++', 'objectivec++']
  },
  'objective-j': {
    type: 'programming',
    extensions: ['.j', '.sj'],
    aliases: ['obj-j', 'objectivej', 'objj']
  },
  objectscript: {
    type: 'programming',
    extensions: ['.cls']
  },
  ocaml: {
    type: 'programming',
    extensions: ['.ml', '.eliom', '.eliomi', '.ml4', '.mli', '.mll', '.mly']
  },
  odin: {
    type: 'programming',
    extensions: ['.odin'],
    aliases: ['odinlang', 'odin-lang']
  },
  omgrofl: {
    type: 'programming',
    extensions: ['.omgrofl']
  },
  'omnet++ msg': {
    type: 'programming',
    extensions: ['.msg'],
    aliases: ['omnetpp-msg']
  },
  'omnet++ ned': {
    type: 'programming',
    extensions: ['.ned'],
    aliases: ['omnetpp-ned']
  },
  ooc: {
    type: 'programming',
    extensions: ['.ooc']
  },
  opa: {
    type: 'programming',
    extensions: ['.opa']
  },
  opal: {
    type: 'programming',
    extensions: ['.opal']
  },
  'open policy agent': {
    type: 'programming',
    extensions: ['.rego']
  },
  'openapi specification v2': {
    type: 'data',
    aliases: ['oasv2']
  },
  'openapi specification v3': {
    type: 'data',
    aliases: ['oasv3']
  },
  opencl: {
    type: 'programming',
    extensions: ['.cl', '.opencl']
  },
  'openedge abl': {
    type: 'programming',
    extensions: ['.p', '.cls', '.w'],
    aliases: ['progress', 'openedge', 'abl']
  },
  openqasm: {
    type: 'programming',
    extensions: ['.qasm']
  },
  'openrc runscript': {
    type: 'programming',
    aliases: ['openrc']
  },
  openscad: {
    type: 'programming',
    extensions: ['.scad']
  },
  'openstep property list': {
    type: 'data',
    extensions: ['.plist', '.glyphs']
  },
  'opentype feature file': {
    type: 'data',
    extensions: ['.fea'],
    aliases: ['AFDKO']
  },
  'option list': {
    type: 'data',
    aliases: ['opts', 'ackrc']
  },
  org: {
    type: 'prose',
    extensions: ['.org']
  },
  overpassql: {
    type: 'programming',
    extensions: ['.overpassql']
  },
  ox: {
    type: 'programming',
    extensions: ['.ox', '.oxh', '.oxo']
  },
  oxygene: {
    type: 'programming',
    extensions: ['.oxygene']
  },
  oz: {
    type: 'programming',
    extensions: ['.oz']
  },
  p4: {
    type: 'programming',
    extensions: ['.p4']
  },
  pact: {
    type: 'programming',
    extensions: ['.pact']
  },
  pan: {
    type: 'programming',
    extensions: ['.pan']
  },
  papyrus: {
    type: 'programming',
    extensions: ['.psc']
  },
  parrot: {
    type: 'programming',
    extensions: ['.parrot']
  },
  'parrot assembly': {
    type: 'programming',
    extensions: ['.pasm'],
    aliases: ['pasm']
  },
  'parrot internal representation': {
    type: 'programming',
    extensions: ['.pir'],
    aliases: ['pir']
  },
  pascal: {
    type: 'programming',
    extensions: ['.pas', '.dfm', '.dpr', '.inc', '.lpr', '.pascal', '.pp'],
    aliases: ['delphi', 'objectpascal']
  },
  pawn: {
    type: 'programming',
    extensions: ['.pwn', '.inc', '.sma']
  },
  pddl: {
    type: 'programming',
    extensions: ['.pddl']
  },
  'peg.js': {
    type: 'programming',
    extensions: ['.pegjs', '.peggy']
  },
  pep8: {
    type: 'programming',
    extensions: ['.pep']
  },
  perl: {
    type: 'programming',
    extensions: ['.pl', '.al', '.cgi', '.fcgi', '.perl', '.ph', '.plx', '.pm', '.psgi', '.t'],
    aliases: ['cperl']
  },
  php: {
    type: 'programming',
    extensions: ['.php', '.aw', '.ctp', '.fcgi', '.inc', '.php3', '.php4', '.php5', '.phps', '.phpt'],
    aliases: ['inc']
  },
  pic: {
    type: 'markup',
    extensions: ['.pic', '.chem'],
    aliases: ['pikchr']
  },
  pickle: {
    type: 'data',
    extensions: ['.pkl']
  },
  picolisp: {
    type: 'programming',
    extensions: ['.l']
  },
  piglatin: {
    type: 'programming',
    extensions: ['.pig']
  },
  pike: {
    type: 'programming',
    extensions: ['.pike', '.pmod']
  },
  pkl: {
    type: 'programming',
    extensions: ['.pkl']
  },
  plantuml: {
    type: 'data',
    extensions: ['.puml', '.iuml', '.plantuml']
  },
  plpgsql: {
    type: 'programming',
    extensions: ['.pgsql', '.sql']
  },
  plsql: {
    type: 'programming',
    extensions: [
      '.pls',
      '.bdy',
      '.ddl',
      '.fnc',
      '.pck',
      '.pkb',
      '.pks',
      '.plb',
      '.plsql',
      '.prc',
      '.spc',
      '.sql',
      '.tpb',
      '.tps',
      '.trg',
      '.vw'
    ]
  },
  pod: {
    type: 'prose',
    extensions: ['.pod']
  },
  'pod 6': {
    type: 'prose',
    extensions: ['.pod', '.pod6']
  },
  pogoscript: {
    type: 'programming',
    extensions: ['.pogo']
  },
  polar: {
    type: 'programming',
    extensions: ['.polar']
  },
  pony: {
    type: 'programming',
    extensions: ['.pony']
  },
  portugol: {
    type: 'programming',
    extensions: ['.por']
  },
  postcss: {
    type: 'markup',
    extensions: ['.pcss', '.postcss']
  },
  postscript: {
    type: 'markup',
    extensions: ['.ps', '.eps', '.epsi', '.pfa'],
    aliases: ['postscr']
  },
  'pov-ray sdl': {
    type: 'programming',
    extensions: ['.pov', '.inc'],
    aliases: ['pov-ray', 'povray']
  },
  powerbuilder: {
    type: 'programming',
    extensions: ['.pbt', '.sra', '.sru', '.srw']
  },
  powershell: {
    type: 'programming',
    extensions: ['.ps1', '.psd1', '.psm1'],
    aliases: ['posh', 'pwsh']
  },
  praat: {
    type: 'programming',
    extensions: ['.praat']
  },
  prisma: {
    type: 'data',
    extensions: ['.prisma']
  },
  processing: {
    type: 'programming',
    extensions: ['.pde']
  },
  proguard: {
    type: 'data',
    extensions: ['.pro']
  },
  prolog: {
    type: 'programming',
    extensions: ['.pl', '.plt', '.pro', '.prolog', '.yap']
  },
  promela: {
    type: 'programming',
    extensions: ['.pml']
  },
  'propeller spin': {
    type: 'programming',
    extensions: ['.spin']
  },
  'protocol buffer': {
    type: 'data',
    extensions: ['.proto'],
    aliases: ['proto', 'protobuf', 'Protocol Buffers']
  },
  'protocol buffer text format': {
    type: 'data',
    extensions: ['.textproto', '.pbt', '.pbtxt'],
    aliases: ['text proto', 'protobuf text format']
  },
  'public key': {
    type: 'data',
    extensions: ['.asc', '.pub']
  },
  pug: {
    type: 'markup',
    extensions: ['.jade', '.pug']
  },
  puppet: {
    type: 'programming',
    extensions: ['.pp']
  },
  'pure data': {
    type: 'data',
    extensions: ['.pd']
  },
  purebasic: {
    type: 'programming',
    extensions: ['.pb', '.pbi']
  },
  purescript: {
    type: 'programming',
    extensions: ['.purs']
  },
  pyret: {
    type: 'programming',
    extensions: ['.arr']
  },
  python: {
    type: 'programming',
    extensions: [
      '.py',
      '.cgi',
      '.fcgi',
      '.gyp',
      '.gypi',
      '.lmi',
      '.py3',
      '.pyde',
      '.pyi',
      '.pyp',
      '.pyt',
      '.pyw',
      '.rpy',
      '.spec',
      '.tac',
      '.wsgi',
      '.xpy'
    ],
    aliases: ['python3', 'rusthon']
  },
  'python console': {
    type: 'programming',
    aliases: ['pycon']
  },
  'python traceback': {
    type: 'data',
    extensions: ['.pytb']
  },
  q: {
    type: 'programming',
    extensions: ['.q']
  },
  'q#': {
    type: 'programming',
    extensions: ['.qs'],
    aliases: ['qsharp']
  },
  qmake: {
    type: 'programming',
    extensions: ['.pro', '.pri']
  },
  qml: {
    type: 'programming',
    extensions: ['.qml', '.qbs']
  },
  'qt script': {
    type: 'programming',
    extensions: ['.qs']
  },
  quickbasic: {
    type: 'programming',
    extensions: ['.bas'],
    aliases: ['qb', 'qbasic', 'qb64', 'classic qbasic', 'classic quickbasic']
  },
  r: {
    type: 'programming',
    extensions: ['.r', '.rd', '.rsx'],
    aliases: ['Rscript', 'splus']
  },
  racket: {
    type: 'programming',
    extensions: ['.rkt', '.rktd', '.rktl', '.scrbl']
  },
  ragel: {
    type: 'programming',
    extensions: ['.rl'],
    aliases: ['ragel-rb', 'ragel-ruby']
  },
  raku: {
    type: 'programming',
    extensions: [
      '.6pl',
      '.6pm',
      '.nqp',
      '.p6',
      '.p6l',
      '.p6m',
      '.pl',
      '.pl6',
      '.pm',
      '.pm6',
      '.raku',
      '.rakumod',
      '.t'
    ],
    aliases: ['perl6', 'perl-6']
  },
  raml: {
    type: 'markup',
    extensions: ['.raml']
  },
  rascal: {
    type: 'programming',
    extensions: ['.rsc']
  },
  'raw token data': {
    type: 'data',
    extensions: ['.raw'],
    aliases: ['raw']
  },
  rbs: {
    type: 'data',
    extensions: ['.rbs']
  },
  rdoc: {
    type: 'prose',
    extensions: ['.rdoc']
  },
  'readline config': {
    type: 'data',
    aliases: ['inputrc', 'readline']
  },
  realbasic: {
    type: 'programming',
    extensions: ['.rbbas', '.rbfrm', '.rbmnu', '.rbres', '.rbtbar', '.rbuistate']
  },
  reason: {
    type: 'programming',
    extensions: ['.re', '.rei']
  },
  reasonligo: {
    type: 'programming',
    extensions: ['.religo']
  },
  rebol: {
    type: 'programming',
    extensions: ['.reb', '.r', '.r2', '.r3', '.rebol']
  },
  red: {
    type: 'programming',
    extensions: ['.red', '.reds'],
    aliases: ['red/system']
  },
  redcode: {
    type: 'programming',
    extensions: ['.cw']
  },
  'redirect rules': {
    type: 'data',
    aliases: ['redirects']
  },
  'regular expression': {
    type: 'data',
    extensions: ['.regexp', '.regex'],
    aliases: ['regexp', 'regex']
  },
  "ren'py": {
    type: 'programming',
    extensions: ['.rpy'],
    aliases: ['renpy']
  },
  renderscript: {
    type: 'programming',
    extensions: ['.rs', '.rsh']
  },
  rescript: {
    type: 'programming',
    extensions: ['.res', '.resi']
  },
  restructuredtext: {
    type: 'prose',
    extensions: ['.rst', '.rest', '.rest.txt', '.rst.txt'],
    aliases: ['rst']
  },
  rexx: {
    type: 'programming',
    extensions: ['.rexx', '.pprx', '.rex'],
    aliases: ['arexx']
  },
  rez: {
    type: 'programming',
    extensions: ['.r']
  },
  'rich text format': {
    type: 'markup',
    extensions: ['.rtf']
  },
  ring: {
    type: 'programming',
    extensions: ['.ring']
  },
  riot: {
    type: 'markup',
    extensions: ['.riot']
  },
  rmarkdown: {
    type: 'prose',
    extensions: ['.qmd', '.rmd']
  },
  robotframework: {
    type: 'programming',
    extensions: ['.robot', '.resource']
  },
  'robots.txt': {
    type: 'data',
    aliases: ['robots', 'robots txt']
  },
  roc: {
    type: 'programming',
    extensions: ['.roc']
  },
  'rocq prover': {
    type: 'programming',
    extensions: ['.v', '.coq'],
    aliases: ['coq', 'rocq']
  },
  roff: {
    type: 'markup',
    extensions: [
      '.roff',
      '.1',
      '.1in',
      '.1m',
      '.1x',
      '.2',
      '.3',
      '.3in',
      '.3m',
      '.3p',
      '.3pm',
      '.3qt',
      '.3x',
      '.4',
      '.5',
      '.6',
      '.7',
      '.8',
      '.9',
      '.l',
      '.man',
      '.mdoc',
      '.me',
      '.ms',
      '.n',
      '.nr',
      '.rno',
      '.tmac'
    ],
    aliases: ['groff', 'man', 'manpage', 'man page', 'man-page', 'mdoc', 'nroff', 'troff']
  },
  'roff manpage': {
    type: 'markup',
    extensions: [
      '.1',
      '.1in',
      '.1m',
      '.1x',
      '.2',
      '.3',
      '.3in',
      '.3m',
      '.3p',
      '.3pm',
      '.3qt',
      '.3x',
      '.4',
      '.5',
      '.6',
      '.7',
      '.8',
      '.9',
      '.man',
      '.mdoc'
    ]
  },
  ron: {
    type: 'data',
    extensions: ['.ron']
  },
  rouge: {
    type: 'programming',
    extensions: ['.rg']
  },
  'routeros script': {
    type: 'programming',
    extensions: ['.rsc']
  },
  rpc: {
    type: 'programming',
    extensions: ['.x'],
    aliases: ['rpcgen', 'oncrpc', 'xdr']
  },
  rpgle: {
    type: 'programming',
    extensions: ['.rpgle', '.sqlrpgle'],
    aliases: ['ile rpg', 'sqlrpgle']
  },
  'rpm spec': {
    type: 'data',
    extensions: ['.spec'],
    aliases: ['specfile']
  },
  ruby: {
    type: 'programming',
    extensions: [
      '.rb',
      '.builder',
      '.eye',
      '.fcgi',
      '.gemspec',
      '.god',
      '.jbuilder',
      '.mspec',
      '.pluginspec',
      '.podspec',
      '.prawn',
      '.rabl',
      '.rake',
      '.rbi',
      '.rbuild',
      '.rbw',
      '.rbx',
      '.ru',
      '.ruby',
      '.spec',
      '.thor',
      '.watchr'
    ],
    aliases: ['jruby', 'macruby', 'rake', 'rb', 'rbx']
  },
  runoff: {
    type: 'markup',
    extensions: ['.rnh', '.rno']
  },
  rust: {
    type: 'programming',
    extensions: ['.rs', '.rs.in'],
    aliases: ['rs']
  },
  sage: {
    type: 'programming',
    extensions: ['.sage', '.sagews']
  },
  sail: {
    type: 'programming',
    extensions: ['.sail']
  },
  saltstack: {
    type: 'programming',
    extensions: ['.sls'],
    aliases: ['saltstate', 'salt']
  },
  sas: {
    type: 'programming',
    extensions: ['.sas']
  },
  sass: {
    type: 'markup',
    extensions: ['.sass']
  },
  scala: {
    type: 'programming',
    extensions: ['.scala', '.kojo', '.sbt', '.sc']
  },
  scaml: {
    type: 'markup',
    extensions: ['.scaml']
  },
  scenic: {
    type: 'programming',
    extensions: ['.scenic']
  },
  scheme: {
    type: 'programming',
    extensions: ['.scm', '.sch', '.sld', '.sls', '.sps', '.ss']
  },
  scilab: {
    type: 'programming',
    extensions: ['.sci', '.sce', '.tst']
  },
  scss: {
    type: 'markup',
    extensions: ['.scss']
  },
  sed: {
    type: 'programming',
    extensions: ['.sed']
  },
  self: {
    type: 'programming',
    extensions: ['.self']
  },
  'selinux policy': {
    type: 'data',
    extensions: ['.te'],
    aliases: ['SELinux Kernel Policy Language', 'sepolicy']
  },
  shaderlab: {
    type: 'programming',
    extensions: ['.shader']
  },
  shell: {
    type: 'programming',
    extensions: [
      '.sh',
      '.bash',
      '.bats',
      '.cgi',
      '.command',
      '.fcgi',
      '.ksh',
      '.sh.in',
      '.tmux',
      '.tool',
      '.trigger',
      '.zsh',
      '.zsh-theme'
    ],
    aliases: ['sh', 'shell-script', 'bash', 'zsh', 'envrc']
  },
  'shellcheck config': {
    type: 'data',
    aliases: ['shellcheckrc']
  },
  shellsession: {
    type: 'programming',
    extensions: ['.sh-session'],
    aliases: ['bash session', 'console']
  },
  shen: {
    type: 'programming',
    extensions: ['.shen']
  },
  sieve: {
    type: 'programming',
    extensions: ['.sieve']
  },
  'simple file verification': {
    type: 'data',
    extensions: ['.sfv'],
    aliases: ['sfv']
  },
  slang: {
    type: 'programming',
    extensions: ['.slang']
  },
  slash: {
    type: 'programming',
    extensions: ['.sl']
  },
  slice: {
    type: 'programming',
    extensions: ['.ice']
  },
  slim: {
    type: 'markup',
    extensions: ['.slim']
  },
  slint: {
    type: 'markup',
    extensions: ['.slint']
  },
  smali: {
    type: 'programming',
    extensions: ['.smali']
  },
  smalltalk: {
    type: 'programming',
    extensions: ['.st', '.cs'],
    aliases: ['squeak']
  },
  smarty: {
    type: 'programming',
    extensions: ['.tpl']
  },
  smithy: {
    type: 'programming',
    extensions: ['.smithy']
  },
  smpl: {
    type: 'programming',
    extensions: ['.cocci'],
    aliases: ['coccinelle']
  },
  smt: {
    type: 'programming',
    extensions: ['.smt2', '.smt', '.z3']
  },
  snakemake: {
    type: 'programming',
    extensions: ['.smk', '.snakefile'],
    aliases: ['snakefile']
  },
  solidity: {
    type: 'programming',
    extensions: ['.sol']
  },
  sourcepawn: {
    type: 'programming',
    extensions: ['.sp', '.inc'],
    aliases: ['sourcemod']
  },
  sparql: {
    type: 'data',
    extensions: ['.sparql', '.rq']
  },
  'spline font database': {
    type: 'data',
    extensions: ['.sfd']
  },
  sqf: {
    type: 'programming',
    extensions: ['.sqf', '.hqf']
  },
  sql: {
    type: 'data',
    extensions: ['.sql', '.cql', '.ddl', '.inc', '.mysql', '.prc', '.tab', '.udf', '.viw']
  },
  sqlpl: {
    type: 'programming',
    extensions: ['.sql', '.db2']
  },
  squirrel: {
    type: 'programming',
    extensions: ['.nut']
  },
  'srecode template': {
    type: 'markup',
    extensions: ['.srt']
  },
  'ssh config': {
    type: 'data',
    aliases: ['sshconfig', 'sshdconfig', 'ssh_config', 'sshd_config']
  },
  stan: {
    type: 'programming',
    extensions: ['.stan']
  },
  'standard ml': {
    type: 'programming',
    extensions: ['.ml', '.fun', '.sig', '.sml'],
    aliases: ['sml']
  },
  star: {
    type: 'data',
    extensions: ['.star']
  },
  starlark: {
    type: 'programming',
    extensions: ['.bzl', '.star'],
    aliases: ['bazel', 'bzl']
  },
  stata: {
    type: 'programming',
    extensions: ['.do', '.ado', '.doh', '.ihlp', '.mata', '.matah', '.sthlp']
  },
  stl: {
    type: 'data',
    extensions: ['.stl'],
    aliases: ['ascii stl', 'stla']
  },
  ston: {
    type: 'data',
    extensions: ['.ston']
  },
  stringtemplate: {
    type: 'markup',
    extensions: ['.st']
  },
  stylus: {
    type: 'markup',
    extensions: ['.styl']
  },
  'subrip text': {
    type: 'data',
    extensions: ['.srt']
  },
  sugarss: {
    type: 'markup',
    extensions: ['.sss']
  },
  supercollider: {
    type: 'programming',
    extensions: ['.sc', '.scd']
  },
  'survex data': {
    type: 'data',
    extensions: ['.svx']
  },
  svelte: {
    type: 'markup',
    extensions: ['.svelte']
  },
  svg: {
    type: 'data',
    extensions: ['.svg']
  },
  sway: {
    type: 'programming',
    extensions: ['.sw']
  },
  sweave: {
    type: 'prose',
    extensions: ['.rnw']
  },
  swift: {
    type: 'programming',
    extensions: ['.swift']
  },
  swig: {
    type: 'programming',
    extensions: ['.i']
  },
  systemverilog: {
    type: 'programming',
    extensions: ['.sv', '.svh', '.vh']
  },
  tact: {
    type: 'programming',
    extensions: ['.tact']
  },
  talon: {
    type: 'programming',
    extensions: ['.talon']
  },
  tcl: {
    type: 'programming',
    extensions: ['.tcl', '.adp', '.sdc', '.tcl.in', '.tm', '.xdc'],
    aliases: ['sdc', 'xdc']
  },
  tcsh: {
    type: 'programming',
    extensions: ['.tcsh', '.csh']
  },
  tea: {
    type: 'markup',
    extensions: ['.tea']
  },
  templ: {
    type: 'markup',
    extensions: ['.templ']
  },
  terra: {
    type: 'programming',
    extensions: ['.t']
  },
  'terraform template': {
    type: 'markup',
    extensions: ['.tftpl']
  },
  tex: {
    type: 'markup',
    extensions: [
      '.tex',
      '.aux',
      '.bbx',
      '.cbx',
      '.cls',
      '.dtx',
      '.ins',
      '.lbx',
      '.ltx',
      '.mkii',
      '.mkiv',
      '.mkvi',
      '.sty',
      '.toc'
    ],
    aliases: ['latex']
  },
  texinfo: {
    type: 'prose',
    extensions: ['.texinfo', '.texi', '.txi']
  },
  text: {
    type: 'prose',
    extensions: ['.txt', '.fr', '.nb', '.ncl', '.no'],
    aliases: ['fundamental', 'plain text']
  },
  textgrid: {
    type: 'data',
    extensions: ['.TextGrid']
  },
  textile: {
    type: 'prose',
    extensions: ['.textile']
  },
  'textmate properties': {
    type: 'data',
    aliases: ['tm-properties']
  },
  thrift: {
    type: 'programming',
    extensions: ['.thrift']
  },
  'ti program': {
    type: 'programming',
    extensions: ['.8xp', '.8xp.txt']
  },
  'tl-verilog': {
    type: 'programming',
    extensions: ['.tlv']
  },
  tla: {
    type: 'programming',
    extensions: ['.tla']
  },
  toit: {
    type: 'programming',
    extensions: ['.toit']
  },
  toml: {
    type: 'data',
    extensions: ['.toml']
  },
  'tor config': {
    type: 'data',
    aliases: ['torrc']
  },
  'tree-sitter query': {
    type: 'programming',
    extensions: ['.scm'],
    aliases: ['tsq']
  },
  'tsplib data': {
    type: 'data',
    extensions: ['.tsp'],
    aliases: ['travelling salesman problem', 'traveling salesman problem']
  },
  tsql: {
    type: 'programming',
    extensions: ['.sql']
  },
  tsv: {
    type: 'data',
    extensions: ['.tsv', '.vcf'],
    aliases: ['tab-seperated values']
  },
  tsx: {
    type: 'programming',
    extensions: ['.tsx']
  },
  turing: {
    type: 'programming',
    extensions: ['.t', '.tu']
  },
  turtle: {
    type: 'data',
    extensions: ['.ttl']
  },
  twig: {
    type: 'markup',
    extensions: ['.twig']
  },
  txl: {
    type: 'programming',
    extensions: ['.txl']
  },
  'type language': {
    type: 'data',
    extensions: ['.tl'],
    aliases: ['tl']
  },
  typescript: {
    type: 'programming',
    extensions: ['.ts', '.cts', '.mts'],
    aliases: ['ts']
  },
  typespec: {
    type: 'programming',
    extensions: ['.tsp'],
    aliases: ['tsp']
  },
  typst: {
    type: 'programming',
    extensions: ['.typ'],
    aliases: ['typ']
  },
  'unified parallel c': {
    type: 'programming',
    extensions: ['.upc']
  },
  'unity3d asset': {
    type: 'data',
    extensions: ['.anim', '.asset', '.mask', '.mat', '.meta', '.prefab', '.unity']
  },
  'unix assembly': {
    type: 'programming',
    extensions: ['.s', '.ms'],
    aliases: ['gas', 'gnu asm', 'unix asm']
  },
  uno: {
    type: 'programming',
    extensions: ['.uno']
  },
  unrealscript: {
    type: 'programming',
    extensions: ['.uc']
  },
  'untyped plutus core': {
    type: 'programming',
    extensions: ['.uplc']
  },
  urweb: {
    type: 'programming',
    extensions: ['.ur', '.urs'],
    aliases: ['Ur/Web', 'Ur']
  },
  v: {
    type: 'programming',
    extensions: ['.v'],
    aliases: ['vlang']
  },
  vala: {
    type: 'programming',
    extensions: ['.vala', '.vapi']
  },
  'valve data format': {
    type: 'data',
    extensions: ['.vdf'],
    aliases: ['keyvalues', 'vdf']
  },
  vba: {
    type: 'programming',
    extensions: ['.bas', '.cls', '.frm', '.vba'],
    aliases: ['visual basic for applications']
  },
  vbscript: {
    type: 'programming',
    extensions: ['.vbs']
  },
  vcard: {
    type: 'data',
    extensions: ['.vcf'],
    aliases: ['virtual contact file', 'electronic business card']
  },
  vcl: {
    type: 'programming',
    extensions: ['.vcl']
  },
  'velocity template language': {
    type: 'markup',
    extensions: ['.vtl'],
    aliases: ['vtl', 'velocity']
  },
  vento: {
    type: 'markup',
    extensions: ['.vto']
  },
  verilog: {
    type: 'programming',
    extensions: ['.v', '.veo']
  },
  vhdl: {
    type: 'programming',
    extensions: ['.vhdl', '.vhd', '.vhf', '.vhi', '.vho', '.vhs', '.vht', '.vhw']
  },
  'vim help file': {
    type: 'prose',
    extensions: ['.txt'],
    aliases: ['help', 'vimhelp']
  },
  'vim script': {
    type: 'programming',
    extensions: ['.vim', '.vba', '.vimrc', '.vmb'],
    aliases: ['vim', 'viml', 'nvim', 'vimscript']
  },
  'vim snippet': {
    type: 'markup',
    extensions: ['.snip', '.snippet', '.snippets'],
    aliases: ['SnipMate', 'UltiSnip', 'UltiSnips', 'NeoSnippet']
  },
  'visual basic .net': {
    type: 'programming',
    extensions: ['.vb', '.vbhtml'],
    aliases: ['visual basic', 'vbnet', 'vb .net', 'vb.net']
  },
  'visual basic 6.0': {
    type: 'programming',
    extensions: ['.bas', '.cls', '.ctl', '.Dsr', '.frm'],
    aliases: ['vb6', 'vb 6', 'visual basic 6', 'visual basic classic', 'classic visual basic']
  },
  volt: {
    type: 'programming',
    extensions: ['.volt']
  },
  vue: {
    type: 'markup',
    extensions: ['.vue']
  },
  vyper: {
    type: 'programming',
    extensions: ['.vy']
  },
  'wavefront material': {
    type: 'data',
    extensions: ['.mtl']
  },
  'wavefront object': {
    type: 'data',
    extensions: ['.obj']
  },
  wdl: {
    type: 'programming',
    extensions: ['.wdl'],
    aliases: ['Workflow Description Language']
  },
  'web ontology language': {
    type: 'data',
    extensions: ['.owl']
  },
  webassembly: {
    type: 'programming',
    extensions: ['.wast', '.wat'],
    aliases: ['wast', 'wasm']
  },
  'webassembly interface type': {
    type: 'data',
    extensions: ['.wit'],
    aliases: ['wit']
  },
  webidl: {
    type: 'programming',
    extensions: ['.webidl']
  },
  webvtt: {
    type: 'data',
    extensions: ['.vtt'],
    aliases: ['vtt']
  },
  'wget config': {
    type: 'data',
    aliases: ['wgetrc']
  },
  wgsl: {
    type: 'programming',
    extensions: ['.wgsl']
  },
  whiley: {
    type: 'programming',
    extensions: ['.whiley']
  },
  wikitext: {
    type: 'prose',
    extensions: ['.mediawiki', '.wiki', '.wikitext'],
    aliases: ['mediawiki', 'wiki']
  },
  'win32 message file': {
    type: 'data',
    extensions: ['.mc']
  },
  'windows registry entries': {
    type: 'data',
    extensions: ['.reg']
  },
  wisp: {
    type: 'programming',
    extensions: ['.wisp']
  },
  'witcher script': {
    type: 'programming',
    extensions: ['.ws']
  },
  wollok: {
    type: 'programming',
    extensions: ['.wlk']
  },
  'world of warcraft addon data': {
    type: 'data',
    extensions: ['.toc']
  },
  wren: {
    type: 'programming',
    extensions: ['.wren'],
    aliases: ['wrenlang']
  },
  'x bitmap': {
    type: 'data',
    extensions: ['.xbm'],
    aliases: ['xbm']
  },
  'x pixmap': {
    type: 'data',
    extensions: ['.xpm', '.pm'],
    aliases: ['xpm']
  },
  x10: {
    type: 'programming',
    extensions: ['.x10'],
    aliases: ['xten']
  },
  xbase: {
    type: 'programming',
    extensions: ['.prg', '.ch', '.prw'],
    aliases: ['advpl', 'clipper', 'foxpro']
  },
  xc: {
    type: 'programming',
    extensions: ['.xc']
  },
  xml: {
    type: 'data',
    extensions: [
      '.xml',
      '.adml',
      '.admx',
      '.ant',
      '.axaml',
      '.axml',
      '.builds',
      '.ccproj',
      '.ccxml',
      '.clixml',
      '.cproject',
      '.cscfg',
      '.csdef',
      '.csl',
      '.csproj',
      '.ct',
      '.depproj',
      '.dita',
      '.ditamap',
      '.ditaval',
      '.dll.config',
      '.dotsettings',
      '.filters',
      '.fsproj',
      '.fxml',
      '.glade',
      '.gml',
      '.gmx',
      '.gpx',
      '.grxml',
      '.gst',
      '.hzp',
      '.iml',
      '.ivy',
      '.jelly',
      '.jsproj',
      '.kml',
      '.launch',
      '.mdpolicy',
      '.mjml',
      '.mm',
      '.mod',
      '.mojo',
      '.mxml',
      '.natvis',
      '.ncl',
      '.ndproj',
      '.nproj',
      '.nuspec',
      '.odd',
      '.osm',
      '.pkgproj',
      '.pluginspec',
      '.proj',
      '.props',
      '.ps1xml',
      '.psc1',
      '.pt',
      '.qhelp',
      '.rdf',
      '.res',
      '.resx',
      '.rs',
      '.rss',
      '.sch',
      '.scxml',
      '.sfproj',
      '.shproj',
      '.slnx',
      '.srdf',
      '.storyboard',
      '.sublime-snippet',
      '.sw',
      '.targets',
      '.tml',
      '.ts',
      '.tsx',
      '.typ',
      '.ui',
      '.urdf',
      '.ux',
      '.vbproj',
      '.vcxproj',
      '.vsixmanifest',
      '.vssettings',
      '.vstemplate',
      '.vxml',
      '.wixproj',
      '.workflow',
      '.wsdl',
      '.wsf',
      '.wxi',
      '.wxl',
      '.wxs',
      '.x3d',
      '.xacro',
      '.xaml',
      '.xib',
      '.xlf',
      '.xliff',
      '.xmi',
      '.xml.dist',
      '.xmp',
      '.xproj',
      '.xsd',
      '.xspec',
      '.xul',
      '.zcml'
    ],
    aliases: ['rss', 'xsd', 'wsdl']
  },
  'xml property list': {
    type: 'data',
    extensions: ['.plist', '.stTheme', '.tmCommand', '.tmLanguage', '.tmPreferences', '.tmSnippet', '.tmTheme']
  },
  xojo: {
    type: 'programming',
    extensions: ['.xojo_code', '.xojo_menu', '.xojo_report', '.xojo_script', '.xojo_toolbar', '.xojo_window']
  },
  xonsh: {
    type: 'programming',
    extensions: ['.xsh']
  },
  xpages: {
    type: 'data',
    extensions: ['.xsp-config', '.xsp.metadata']
  },
  xproc: {
    type: 'programming',
    extensions: ['.xpl', '.xproc']
  },
  xquery: {
    type: 'programming',
    extensions: ['.xquery', '.xq', '.xql', '.xqm', '.xqy']
  },
  xs: {
    type: 'programming',
    extensions: ['.xs']
  },
  xslt: {
    type: 'programming',
    extensions: ['.xslt', '.xsl'],
    aliases: ['xsl']
  },
  xtend: {
    type: 'programming',
    extensions: ['.xtend']
  },
  yacc: {
    type: 'programming',
    extensions: ['.y', '.yacc', '.yy']
  },
  yaml: {
    type: 'data',
    extensions: [
      '.yml',
      '.mir',
      '.reek',
      '.rviz',
      '.sublime-syntax',
      '.syntax',
      '.yaml',
      '.yaml-tmlanguage',
      '.yaml.sed',
      '.yml.mysql'
    ],
    aliases: ['yml']
  },
  yang: {
    type: 'data',
    extensions: ['.yang']
  },
  yara: {
    type: 'programming',
    extensions: ['.yar', '.yara']
  },
  yasnippet: {
    type: 'markup',
    extensions: ['.yasnippet'],
    aliases: ['snippet', 'yas']
  },
  yul: {
    type: 'programming',
    extensions: ['.yul']
  },
  zap: {
    type: 'programming',
    extensions: ['.zap', '.xzap']
  },
  zeek: {
    type: 'programming',
    extensions: ['.zeek', '.bro'],
    aliases: ['bro']
  },
  zenscript: {
    type: 'programming',
    extensions: ['.zs']
  },
  zephir: {
    type: 'programming',
    extensions: ['.zep']
  },
  zig: {
    type: 'programming',
    extensions: ['.zig', '.zig.zon']
  },
  zil: {
    type: 'programming',
    extensions: ['.zil', '.mud']
  },
  zimpl: {
    type: 'programming',
    extensions: ['.zimpl', '.zmpl', '.zpl']
  },
  zmodel: {
    type: 'data',
    extensions: ['.zmodel']
  }
}
