/**
 * Auto-generated boot config schema
 * Generated at: 2026-04-07T11:48:16.501Z
 *
 * This file is automatically generated from classification.json
 * To update this file, modify classification.json and run:
 * node v2-refactor-temp/tools/data-classify/scripts/generate-boot-config.js
 *
 * === AUTO-GENERATED CONTENT START ===
 */

export interface BootConfigSchema {
  // redux/settings/disableHardwareAcceleration
  'app.disable_hardware_acceleration': boolean
}

export const DefaultBootConfig: BootConfigSchema = {
  'app.disable_hardware_acceleration': false
}

// === AUTO-GENERATED CONTENT END ===
