/**
 * One-time data backfills that run after Drizzle's `migrate()` pass.
 *
 * Each backfill MUST be idempotent: it re-runs on every boot and should be a
 * no-op once the data is in its target shape. Detection is via cheap SELECT
 * for sentinel values (e.g. `order_key = ''`) — no separate tracking table.
 *
 * Why not pure SQL inside the migration file? Fractional-indexing keys are
 * generated by a JS library (`fractional-indexing` via `generateOrderKeySequence`)
 * and cannot be produced by SQL alone. The migration sets a sentinel default
 * (`''`); this module upgrades it to canonical keys.
 *
 * Spec: docs/references/data/data-ordering-guide.md §7 step 6.
 */
import { generateOrderKeySequence } from '@data/services/utils/orderKey'
import { loggerService } from '@logger'
import { sql } from 'drizzle-orm'

import type { DbOrTx, DbType } from './types'

const logger = loggerService.withContext('DbPostMigrateBackfills')

export async function runPostMigrateBackfills(db: DbType): Promise<void> {
  await backfillTopicOrderKey(db)
  await backfillPinOrderKey(db)
}

/**
 * Upgrade `topic.order_key = ''` (sentinel from migration 0015) to canonical
 * fractional-indexing keys, partitioned by `group_id` and ordered by
 * `updated_at DESC` within each partition (matches the default unpinned-list
 * sort, so first reorders feel natural).
 */
async function backfillTopicOrderKey(db: DbType): Promise<void> {
  const result = await db.run(sql`
    SELECT id, group_id AS groupId
    FROM topic
    WHERE order_key = ''
    ORDER BY (group_id IS NULL) DESC, group_id, updated_at DESC, id ASC
  `)
  const rows = result.rows as unknown as Array<{ id: string; groupId: string | null }>
  if (rows.length === 0) return

  const buckets = new Map<string | null, string[]>()
  for (const r of rows) {
    const list = buckets.get(r.groupId)
    if (list) list.push(r.id)
    else buckets.set(r.groupId, [r.id])
  }

  await db.transaction(async (tx: DbOrTx) => {
    for (const ids of buckets.values()) {
      const keys = generateOrderKeySequence(ids.length)
      for (let i = 0; i < ids.length; i++) {
        await tx.run(sql`UPDATE topic SET order_key = ${keys[i]} WHERE id = ${ids[i]}`)
      }
    }
  })

  logger.info('Backfilled topic.order_key', { rowCount: rows.length, partitionCount: buckets.size })
}

/**
 * Upgrade `pin.order_key = ''` (sentinel from migration 0015 step 2 and any
 * future migrations using the same sentinel) to canonical fractional-indexing
 * keys, partitioned by `entity_type`. Sort within partition by the source
 * topic's `updated_at DESC` when the pin was emitted from a topic; for non-
 * topic entityTypes (none today, future-proof) fall back to `pin.created_at`.
 */
async function backfillPinOrderKey(db: DbType): Promise<void> {
  const result = await db.run(sql`
    SELECT pin.id AS id, pin.entity_type AS entityType
    FROM pin
    LEFT JOIN topic ON pin.entity_type = 'topic' AND pin.entity_id = topic.id
    WHERE pin.order_key = ''
    ORDER BY pin.entity_type, COALESCE(topic.updated_at, pin.created_at) DESC, pin.id ASC
  `)
  const rows = result.rows as unknown as Array<{ id: string; entityType: string }>
  if (rows.length === 0) return

  const buckets = new Map<string, string[]>()
  for (const r of rows) {
    const list = buckets.get(r.entityType)
    if (list) list.push(r.id)
    else buckets.set(r.entityType, [r.id])
  }

  await db.transaction(async (tx: DbOrTx) => {
    for (const ids of buckets.values()) {
      const keys = generateOrderKeySequence(ids.length)
      for (let i = 0; i < ids.length; i++) {
        await tx.run(sql`UPDATE pin SET order_key = ${keys[i]} WHERE id = ${ids[i]}`)
      }
    }
  })

  logger.info('Backfilled pin.order_key', { rowCount: rows.length, partitionCount: buckets.size })
}
