/**
 * Auto-generated icon meta catalog for synchronous runtime lookup
 * Do not edit manually — regenerated by the icon pipeline
 *
 * Generated at: 2026-07-15T10:44:58.420Z
 * Total icons: 115
 */
import { type IconMeta } from '../types'
import { meta as aceMeta } from './ace/meta'
import { meta as adobeMeta } from './adobe/meta'
import { meta as ai2Meta } from './ai2/meta'
import { meta as ai21Meta } from './ai21/meta'
import { meta as ai360Meta } from './ai360/meta'
import { meta as aihubmixMeta } from './aihubmix/meta'
import { meta as aimassMeta } from './aimass/meta'
import { meta as aionlabsMeta } from './aionlabs/meta'
import { meta as anthropicMeta } from './anthropic/meta'
import { meta as arceeMeta } from './arcee/meta'
import { meta as assemblyaiMeta } from './assemblyai/meta'
import { meta as awsMeta } from './aws/meta'
import { meta as ayaMeta } from './aya/meta'
import { meta as baaiMeta } from './baai/meta'
import { meta as baichuanMeta } from './baichuan/meta'
import { meta as baiducloudMeta } from './baiducloud/meta'
import { meta as bilibiliMeta } from './bilibili/meta'
import { meta as bilibiliindexMeta } from './bilibiliindex/meta'
import { meta as burncloudMeta } from './burncloud/meta'
import { meta as bytedanceMeta } from './bytedance/meta'
import { meta as chatglmMeta } from './chatglm/meta'
import { meta as claudeMeta } from './claude/meta'
import { meta as codegeexMeta } from './codegeex/meta'
import { meta as cogviewMeta } from './cogview/meta'
import { meta as cohereMeta } from './cohere/meta'
import { meta as dalleMeta } from './dalle/meta'
import { meta as dbrxMeta } from './dbrx/meta'
import { meta as deepcogitoMeta } from './deepcogito/meta'
import { meta as deepmindMeta } from './deepmind/meta'
import { meta as deepseekMeta } from './deepseek/meta'
import { meta as dolphinMeta } from './dolphin/meta'
import { meta as doubaoMeta } from './doubao/meta'
import { meta as essentialaiMeta } from './essentialai/meta'
import { meta as fireworksMeta } from './fireworks/meta'
import { meta as fishaudioMeta } from './fishaudio/meta'
import { meta as fluxMeta } from './flux/meta'
import { meta as geminiMeta } from './gemini/meta'
import { meta as gemmaMeta } from './gemma/meta'
import { meta as glmMeta } from './glm/meta'
import { meta as glmvMeta } from './glmv/meta'
import { meta as googleMeta } from './google/meta'
import { meta as gpt5Meta } from './gpt-5/meta'
import { meta as gpt51Meta } from './gpt-5-1/meta'
import { meta as gpt51ChatMeta } from './gpt-5-1-chat/meta'
import { meta as gpt51CodexMeta } from './gpt-5-1-codex/meta'
import { meta as gpt51CodexMiniMeta } from './gpt-5-1-codex-mini/meta'
import { meta as gpt52Meta } from './gpt-5-2/meta'
import { meta as gpt52ProMeta } from './gpt-5-2-pro/meta'
import { meta as gpt5ChatMeta } from './gpt-5-chat/meta'
import { meta as gpt5CodexMeta } from './gpt-5-codex/meta'
import { meta as gpt5MiniMeta } from './gpt-5-mini/meta'
import { meta as gpt5NanoMeta } from './gpt-5-nano/meta'
import { meta as gptImage1Meta } from './gpt-image-1/meta'
import { meta as gptImage15Meta } from './gpt-image-1-5/meta'
import { meta as gptOss20bMeta } from './gpt-oss-20b/meta'
import { meta as gptOss120bMeta } from './gpt-oss-120b/meta'
import { meta as grokMeta } from './grok/meta'
import { meta as hailuoMeta } from './hailuo/meta'
import { meta as hunyuanMeta } from './hunyuan/meta'
import { meta as ibmMeta } from './ibm/meta'
import { meta as ideogramMeta } from './ideogram/meta'
import { meta as inceptionMeta } from './inception/meta'
import { meta as inflectionMeta } from './inflection/meta'
import { meta as internlmMeta } from './internlm/meta'
import { meta as jimengMeta } from './jimeng/meta'
import { meta as jinaMeta } from './jina/meta'
import { meta as kimiMeta } from './kimi/meta'
import { meta as klingMeta } from './kling/meta'
import { meta as kolorsMeta } from './kolors/meta'
import { meta as kwaipilotMeta } from './kwaipilot/meta'
import { meta as lgMeta } from './lg/meta'
import { meta as lingMeta } from './ling/meta'
import { meta as liquidMeta } from './liquid/meta'
import { meta as llavaMeta } from './llava/meta'
import { meta as longcatMeta } from './longcat/meta'
import { meta as menloMeta } from './menlo/meta'
import { meta as metaMeta } from './meta/meta'
import { meta as microsoftMeta } from './microsoft/meta'
import { meta as mimoMeta } from './mimo/meta'
import { meta as minimaxMeta } from './minimax/meta'
import { meta as mistralMeta } from './mistral/meta'
import { meta as moonshotMeta } from './moonshot/meta'
import { meta as morphMeta } from './morph/meta'
import { meta as nanobananaMeta } from './nanobanana/meta'
import { meta as nousresearchMeta } from './nousresearch/meta'
import { meta as novaMeta } from './nova/meta'
import { meta as nvidiaMeta } from './nvidia/meta'
import { meta as openaiMeta } from './openai/meta'
import { meta as openchatMeta } from './openchat/meta'
import { meta as openrouterMeta } from './openrouter/meta'
import { meta as palmMeta } from './palm/meta'
import { meta as perplexityMeta } from './perplexity/meta'
import { meta as phindMeta } from './phind/meta'
import { meta as qiniuMeta } from './qiniu/meta'
import { meta as qwenMeta } from './qwen/meta'
import { meta as relaceMeta } from './relace/meta'
import { meta as rwkvMeta } from './rwkv/meta'
import { meta as sensenovaMeta } from './sensenova/meta'
import { meta as skyworkMeta } from './skywork/meta'
import { meta as soraMeta } from './sora/meta'
import { meta as sparkMeta } from './spark/meta'
import { meta as stabilityMeta } from './stability/meta'
import { meta as stepfunMeta } from './stepfun/meta'
import { meta as sunoMeta } from './suno/meta'
import { meta as tiiMeta } from './tii/meta'
import { meta as trinityMeta } from './trinity/meta'
import { meta as udioMeta } from './udio/meta'
import { meta as upstageMeta } from './upstage/meta'
import { meta as v0Meta } from './v0/meta'
import { meta as vertexaiMeta } from './vertexai/meta'
import { meta as voyageMeta } from './voyage/meta'
import { meta as wenxinMeta } from './wenxin/meta'
import { meta as xiaomimimoMeta } from './xiaomimimo/meta'
import { meta as yiMeta } from './yi/meta'
import { meta as zaiMeta } from './zai/meta'

export const MODEL_ICON_META_CATALOG = {
  ace: aceMeta,
  adobe: adobeMeta,
  ai2: ai2Meta,
  ai21: ai21Meta,
  ai360: ai360Meta,
  aihubmix: aihubmixMeta,
  aimass: aimassMeta,
  aionlabs: aionlabsMeta,
  anthropic: anthropicMeta,
  arcee: arceeMeta,
  assemblyai: assemblyaiMeta,
  aws: awsMeta,
  aya: ayaMeta,
  baai: baaiMeta,
  baichuan: baichuanMeta,
  baiducloud: baiducloudMeta,
  bilibili: bilibiliMeta,
  bilibiliindex: bilibiliindexMeta,
  burncloud: burncloudMeta,
  bytedance: bytedanceMeta,
  chatglm: chatglmMeta,
  claude: claudeMeta,
  codegeex: codegeexMeta,
  cogview: cogviewMeta,
  cohere: cohereMeta,
  dalle: dalleMeta,
  dbrx: dbrxMeta,
  deepcogito: deepcogitoMeta,
  deepmind: deepmindMeta,
  deepseek: deepseekMeta,
  dolphin: dolphinMeta,
  doubao: doubaoMeta,
  essentialai: essentialaiMeta,
  fireworks: fireworksMeta,
  fishaudio: fishaudioMeta,
  flux: fluxMeta,
  gemini: geminiMeta,
  gemma: gemmaMeta,
  glm: glmMeta,
  glmv: glmvMeta,
  google: googleMeta,
  'gpt-5': gpt5Meta,
  'gpt-5-1': gpt51Meta,
  'gpt-5-1-chat': gpt51ChatMeta,
  'gpt-5-1-codex': gpt51CodexMeta,
  'gpt-5-1-codex-mini': gpt51CodexMiniMeta,
  'gpt-5-2': gpt52Meta,
  'gpt-5-2-pro': gpt52ProMeta,
  'gpt-5-chat': gpt5ChatMeta,
  'gpt-5-codex': gpt5CodexMeta,
  'gpt-5-mini': gpt5MiniMeta,
  'gpt-5-nano': gpt5NanoMeta,
  'gpt-image-1': gptImage1Meta,
  'gpt-image-1-5': gptImage15Meta,
  'gpt-oss-120b': gptOss120bMeta,
  'gpt-oss-20b': gptOss20bMeta,
  grok: grokMeta,
  hailuo: hailuoMeta,
  hunyuan: hunyuanMeta,
  ibm: ibmMeta,
  ideogram: ideogramMeta,
  inception: inceptionMeta,
  inflection: inflectionMeta,
  internlm: internlmMeta,
  jimeng: jimengMeta,
  jina: jinaMeta,
  kimi: kimiMeta,
  kling: klingMeta,
  kolors: kolorsMeta,
  kwaipilot: kwaipilotMeta,
  lg: lgMeta,
  ling: lingMeta,
  liquid: liquidMeta,
  llava: llavaMeta,
  longcat: longcatMeta,
  menlo: menloMeta,
  meta: metaMeta,
  microsoft: microsoftMeta,
  mimo: mimoMeta,
  minimax: minimaxMeta,
  mistral: mistralMeta,
  moonshot: moonshotMeta,
  morph: morphMeta,
  nanobanana: nanobananaMeta,
  nousresearch: nousresearchMeta,
  nova: novaMeta,
  nvidia: nvidiaMeta,
  openai: openaiMeta,
  openchat: openchatMeta,
  openrouter: openrouterMeta,
  palm: palmMeta,
  perplexity: perplexityMeta,
  phind: phindMeta,
  qiniu: qiniuMeta,
  qwen: qwenMeta,
  relace: relaceMeta,
  rwkv: rwkvMeta,
  sensenova: sensenovaMeta,
  skywork: skyworkMeta,
  sora: soraMeta,
  spark: sparkMeta,
  stability: stabilityMeta,
  stepfun: stepfunMeta,
  suno: sunoMeta,
  tii: tiiMeta,
  trinity: trinityMeta,
  udio: udioMeta,
  upstage: upstageMeta,
  v0: v0Meta,
  vertexai: vertexaiMeta,
  voyage: voyageMeta,
  wenxin: wenxinMeta,
  xiaomimimo: xiaomimimoMeta,
  yi: yiMeta,
  zai: zaiMeta
} as const satisfies Record<string, IconMeta>

export type ModelIconKey = keyof typeof MODEL_ICON_META_CATALOG
