/**
 * Follow-up queue entity types.
 *
 * A queued follow-up is a composer draft captured mid-stream, drained into a
 * real send when the turn goes idle. Rows are keyed by an opaque conversation
 * scope string (`${topicId}:${assistantId}` for chat, `agent-session:${sessionId}`
 * for agent sessions) — the queue table never interprets the scope, and purge
 * on conversation delete matches by scope prefix.
 */

import * as z from 'zod'

import type { ComposerQueuedMessagePayload } from '@shared/ai/transport'

// ============================================================================
// Scope keys
// ============================================================================

/** Fallback assistant segment when a chat topic has no assistant selected. */
export const FOLLOWUP_NO_ASSISTANT = 'no-assistant'

/** Prefix identifying agent-session scope keys. Mirrors `buildAgentSessionTopicId`. */
export const FOLLOWUP_SESSION_SCOPE_PREFIX = 'agent-session:'

/** Build the queue scope key for a chat topic. */
export function buildTopicFollowupScopeKey(topicId: string, assistantId?: string | null): string {
  return `${topicId}:${assistantId ?? FOLLOWUP_NO_ASSISTANT}`
}

/** Prefix matching every queue row that belongs to a chat topic. */
export function topicFollowupScopePrefix(topicId: string): string {
  return `${topicId}:`
}

/**
 * Prefix matching every queue row that belongs to an agent session. No
 * trailing separator: today's session scope is exactly
 * `agent-session:${sessionId}`, and the prefix also covers any future
 * `:`-suffixed extension. Safe because session ids are fixed-length UUIDs —
 * one id can never be a strict prefix of another.
 */
export function sessionFollowupScopePrefix(sessionId: string): string {
  return `${FOLLOWUP_SESSION_SCOPE_PREFIX}${sessionId}`
}

/** Maximum queued follow-ups per conversation scope, enforced at the write path. */
export const FOLLOWUP_QUEUE_LIMIT = 20

/** Canonical membership dimension for `/followup-queues` change effects. */
export const FOLLOWUP_QUEUE_SCOPE_DIMENSION = 'scopeKey'

export const FollowupQueueScopeKeySchema = z.string().min(1)
export type FollowupQueueScopeKey = z.infer<typeof FollowupQueueScopeKeySchema>

export const FollowupQueueIdSchema = z.uuid()
export type FollowupQueueId = z.infer<typeof FollowupQueueIdSchema>

// ============================================================================
// Queue item entity
// ============================================================================

/**
 * Drain status driving cross-window send arbitration. `pending` and `failed`
 * rows are claimable; `sending` rows are owned by the claiming window until
 * the send resolves (delete) or fails (back to `failed`).
 */
export const FollowupQueueStatusSchema = z.enum(['pending', 'sending', 'failed'])
export type FollowupQueueStatus = z.infer<typeof FollowupQueueStatusSchema>

/**
 * Serialized composer draft. Structural check only: the token entry types
 * stay renderer-owned, main only stores and returns this blob.
 */
export interface FollowupQueueDraft {
  text: string
  tokens: Array<{
    id: string
    kind: string
    label: string
    icon?: string
    description?: string
    promptText?: string
    payload?: unknown
  }>
}

export const FollowupQueueDraftSchema = z.custom<FollowupQueueDraft>((value) => {
  if (typeof value !== 'object' || value === null) return false
  const v = value as Partial<FollowupQueueDraft>
  if (typeof v.text !== 'string' || !Array.isArray(v.tokens)) return false
  return v.tokens.every(
    (token) =>
      typeof token === 'object' &&
      token !== null &&
      typeof (token as { id?: unknown }).id === 'string' &&
      typeof (token as { kind?: unknown }).kind === 'string' &&
      typeof (token as { label?: unknown }).label === 'string'
  )
})

/**
 * Send-ready payload captured at enqueue time. Structural check only — part
 * entry types stay owned by the transport layer, main never interprets them.
 */
export const FollowupQueuePayloadSchema = z.custom<ComposerQueuedMessagePayload>((value) => {
  if (typeof value !== 'object' || value === null) return false
  const v = value as Partial<ComposerQueuedMessagePayload>
  return typeof v.text === 'string' && Array.isArray(v.userMessageParts)
})

/** Complete queue item as returned by the API. */
export const FollowupQueueItemSchema = z.strictObject({
  /** Queue item ID (UUID v7, auto-generated by database) */
  id: FollowupQueueIdSchema,
  /** Opaque conversation scope key (see builders above) */
  scopeKey: FollowupQueueScopeKeySchema,
  /** Serialized draft (text + tokens) — drives the dock preview and edit-restore */
  draft: FollowupQueueDraftSchema,
  /** Send-ready payload captured at enqueue time */
  payload: FollowupQueuePayloadSchema,
  /** Drain status for cross-window send arbitration */
  status: FollowupQueueStatusSchema,
  /** Fractional-indexing order key within this scopeKey */
  orderKey: z.string().min(1),
  /** Creation timestamp (ISO string) */
  createdAt: z.iso.datetime(),
  /** Last update timestamp (ISO string) */
  updatedAt: z.iso.datetime()
})
export type FollowupQueueItem = z.infer<typeof FollowupQueueItemSchema>

// ============================================================================
// Per-scope paused state
// ============================================================================

/** Auto-drain paused flag for one conversation scope. */
export const FollowupQueueStateSchema = z.strictObject({
  /** Opaque conversation scope key (see builders above) */
  scopeKey: FollowupQueueScopeKeySchema,
  /** Whether auto-drain is paused for this scope */
  paused: z.boolean(),
  /** Creation timestamp (ISO string) */
  createdAt: z.iso.datetime(),
  /** Last update timestamp (ISO string) */
  updatedAt: z.iso.datetime()
})
export type FollowupQueueState = z.infer<typeof FollowupQueueStateSchema>
