import React from 'react'
import { useTranslation } from 'react-i18next'

import { isUniqueModelId, parseUniqueModelId } from '@shared/data/types/model'
import type { ModelFallbackPartData } from '@shared/data/types/uiParts'

/** Display id: the model half of a `providerId::modelId` UniqueModelId. Splits on the FIRST
 *  separator — a modelId may itself contain `::`, so the last segment is not the model half. */
function toDisplayModelId(uniqueModelId: string): string {
  if (!isUniqueModelId(uniqueModelId)) return uniqueModelId
  return parseUniqueModelId(uniqueModelId).modelId
}

/**
 * Divider marking where the turn failed over to a fallback model before producing any content —
 * the reply below it was generated by the fallback model, not the agent's configured one.
 */
const ModelFallbackBlock: React.FC<{ data?: ModelFallbackPartData }> = ({ data }) => {
  const { t } = useTranslation()

  return (
    <div className="my-3 flex w-full items-center gap-3 text-muted-foreground" role="separator">
      <span className="h-px min-w-6 flex-1 border-t border-dashed border-border-subtle" aria-hidden />
      <span className="shrink-0 text-xs">
        {t('message.model_fallback', {
          reason: data?.reason,
          model: data ? toDisplayModelId(data.to) : undefined
        })}
      </span>
      <span className="h-px min-w-6 flex-1 border-t border-dashed border-border-subtle" aria-hidden />
    </div>
  )
}

export default React.memo(ModelFallbackBlock)
