import type { SerializedError } from '@shared/types/error'
import type { UIMessageChunk } from 'ai'

import type { PendingMessageQueue } from '../PendingMessageQueue'

// ── StreamDoneResult ────────────────────────────────────────────────

/**
 * Terminal state passed to each sink when a stream ends.
 *
 * Distinguishes "completed normally" from "user aborted mid-flight with partial
 * output" — preserving the v1 `ChatSession.handleFinish` success/paused semantics.
 */
export interface StreamDoneResult {
  finalMessage?: CherryUIMessage
  /** 'success' = natural completion; 'paused' = abort path with partial result. */
  status: 'success' | 'paused'
}

// ── StreamTarget ────────────────────────────────────────────────────

/**
 * Minimal subset of `Electron.WebContents` that `AiService.executeStream` uses.
 *
 * `send` / `isDestroyed` are the two methods already on real `WebContents`.
 * `setFinalMessage` is a Broker-only extension — upstream (agentLoop or
 * ClaudeCodeStreamAdapter) passes the completed UIMessage through this setter
 * so the Broker does not have to reconstruct it from chunks.
 *
 * Defined here (not in BrokerStreamTarget.ts) because:
 *  1. AiService.executeStream will use it as parameter type — it is the Phase 2
 *     decoupling interface between AiService and the Broker.
 *  2. Unit tests can implement a MockStreamTarget without importing Broker internals.
 */
export interface StreamTarget {
  send(channel: string, payload: { chunk?: UIMessageChunk; error?: SerializedError }): void
  isDestroyed(): boolean
  /** Optional: upstream writes the full UIMessage here before signaling done. */
  setFinalMessage?(message: CherryUIMessage): void
}

// ── StreamSink ──────────────────────────────────────────────────────

/**
 * Consumer abstraction. The Broker dispatches to sinks uniformly — it never
 * inspects a sink's concrete type.
 *
 * Any internal state / classification is encapsulated inside the implementation.
 */
export interface StreamSink {
  /**
   * Stable unique identifier used for:
   *  - dedup within the sinks Map (same subscriber → upsert, not duplicate)
   *  - detach by exact match
   *  - logging / tracing
   *
   * Implementor guarantees uniqueness. The Broker never parses its content.
   */
  readonly id: string

  onChunk(chunk: UIMessageChunk): void
  /**
   * Stream ended (success or paused). See {@link StreamDoneResult} for semantics.
   */
  onDone(result: StreamDoneResult): void | Promise<void>
  onError(error: SerializedError): void | Promise<void>

  /**
   * Liveness check — **not** a lifecycle phase.
   *
   * The Broker calls `isAlive()` before each multicast. Returning `false`
   * causes the sink to be immediately removed from the sinks Map.
   *
   * Typical implementations:
   *  - WebContentsSink  → `!wc.isDestroyed()`
   *  - ChannelAdapterSink → `adapter.connected`
   *  - PersistenceSink  → always `true` (lives until stream is reaped)
   */
  isAlive(): boolean
}

// ── ActiveStream ────────────────────────────────────────────────────

/**
 * Runtime state for one generation attempt, keyed by `requestId` in the
 * Broker's main Map.
 */
export interface ActiveStream {
  /**
   * Control-plane identity — one generation attempt = one requestId.
   *
   * Generated by Renderer (`crypto.randomUUID()`) and carried in
   * `AiStreamOpenRequest.requestId`. The Broker uses it as:
   *  - primary Map key (`activeStreams`)
   *  - abort / attach / detach routing target
   *  - in-memory dedup key (rapid retry → same requestId → noop)
   */
  requestId: string

  /** Data-plane identity — the Cherry Studio conversation this stream belongs to. */
  topicId: string

  /**
   * Owned by the Broker, independent of any Renderer lifecycle.
   * Passed to AiService as `options.signal`.
   */
  abortController: AbortController

  /** All consumers. Key = sink.id. */
  sinks: Map<string, StreamSink>

  /**
   * Steering queue — messages the user sends *while this stream is still running*.
   *
   * `runAgentLoop.prepareStep` drains this between inner iterations to fold
   * new user messages into the next context window.
   */
  pendingMessages: PendingMessageQueue

  /** Ordered chunk buffer for reconnect replay. */
  buffer: UIMessageChunk[]

  status: 'streaming' | 'done' | 'error' | 'aborted'

  /**
   * Full UIMessage set by upstream via `BrokerStreamTarget.setFinalMessage()`
   * before the stream ends. May be `undefined` if upstream didn't provide one.
   */
  finalMessage?: CherryUIMessage

  error?: SerializedError

  /** Grace-period reap timestamp (ms since epoch). */
  reapAt?: number
  /** Timer handle for `scheduleReap`, so `evictStream` can cancel it. */
  reapTimer?: ReturnType<typeof setTimeout>

  /**
   * Backend-specific resume token (currently only used by ClaudeCodeService).
   *
   * Claude Agent SDK's init message carries a `session_id` that can be passed
   * back for resume. The adapter writes it here; `startStream` reads it back
   * when the topic has a previous stream being evicted.
   */
  sourceSessionId?: string
}

// ── Config ──────────────────────────────────────────────────────────

export interface AiStreamBrokerConfig {
  /** How long a finished stream stays in memory for late reconnects. */
  readonly gracePeriodMs: number // default 30_000
  /** What to do when all subscribers disconnect mid-stream. */
  readonly backgroundMode: 'continue' | 'abort' // default 'continue'
  /** Per-stream buffer cap; exceeding this stops buffering (not streaming). */
  readonly maxBufferChunks: number // default 10_000
}

// ── IPC payloads ────────────────────────────────────────────────────

/** Main → Renderer: a single chunk of a running stream. */
export interface BrokerStreamChunkPayload {
  topicId: string
  chunk: UIMessageChunk
}

/** Main → Renderer: stream ended. */
export interface BrokerStreamDonePayload {
  topicId: string
  status: 'success' | 'paused'
}

/** Main → Renderer: stream error. */
export interface BrokerStreamErrorPayload {
  topicId: string
  error: SerializedError
}

/** Renderer → Main: open a new stream or steer an existing one. */
export interface AiStreamOpenRequest {
  requestId: string
  topicId: string
  parentAnchorId: string | null
  userMessage: {
    role: 'user'
    data: { parts: unknown[] }
  }
  assistantId: string
  // Remaining fields from AiStreamRequest (model, tools, config, etc.)
  // are inherited at call sites — Broker passes the whole object through to
  // AiService.executeStream without inspecting these.
  [key: string]: unknown
}

/** Renderer → Main: reconnect to a running or recently-finished stream. */
export type AiStreamAttachRequest = { mode: 'byRequestId'; requestId: string } | { mode: 'byTopicId'; topicId: string }

/** Renderer → Main: unsubscribe from a stream (stream keeps running). */
export interface AiStreamDetachRequest {
  requestId: string
}

/** Renderer → Main: abort a specific generation attempt. */
export interface AiStreamAbortRequest {
  requestId: string
}

/** Main → Renderer: result of an attach attempt. */
export type AiStreamAttachResponse =
  | { status: 'not-found' }
  | { status: 'attached'; requestId: string; replayedChunks: number }
  | { status: 'done'; requestId: string; finalMessage: CherryUIMessage }
  | { status: 'error'; requestId: string; error: SerializedError }

// ── Placeholder type ────────────────────────────────────────────────

// TODO: Replace with the real CherryUIMessage type from AI SDK / shared once
// the Phase 1 block-to-part migration (Step 1.2) is complete.
// For now this is a structural placeholder so the file compiles.

export interface CherryUIMessage {
  [key: string]: unknown
}
