/**
 * Auto-generated boot config schema
 * Generated at: 2026-07-19T07:26:03.702Z
 *
 * This file is automatically generated from classification.json (plus a
 * small MANUAL_BOOT_CONFIG_ITEMS list in generate-boot-config.js for keys
 * that don't fit classification.json's model yet, e.g. config-file sources).
 *
 * The zod schema is the single source of truth: the BootConfigSchema type
 * is inferred from it, and BootConfigService validates file/set values
 * against it at runtime.
 *
 * To update this file, either modify classification.json or the manual list
 * in the generator, then run:
 * node v2-refactor-temp/tools/data-classify/scripts/generate-boot-config.js
 *
 * === AUTO-GENERATED CONTENT START ===
 */

import * as z from 'zod'

export const bootConfigSchema = z.object({
  // redux/settings/disableHardwareAcceleration
  'app.disable_hardware_acceleration': z.boolean(),

  /**
   * Custom user data directory, keyed by executable path.
   *
   * Conceptually a single setting ("where user data lives"); stored as a
   * Record so the same machine can host multiple installations (stable / dev /
   * portable) with independent user data locations — matching the v1 behavior
   * of ~/.cherrystudio/config/config.json's `appDataPath` array.
   *
   * Key: normalized executable path from getNormalizedExecutablePath() —
   * intentionally not `app.getPath('exe')` for Linux AppImage and Windows
   * portable builds, whose raw exe paths are unstable across launches.
   * Value: absolute path to the chosen userData directory.
   *
   * Migrated from v1 ~/.cherrystudio/config/config.json on first v1→v2 run
   * via the 'configfile' source in BootConfigMigrator.
   */
  // configfile/legacy-home/appDataPath
  'app.user_data_path': z.record(z.string(), z.string()),

  /**
   * Pending factory reset of the app (issue #17131): on the next boot,
   * the preboot factory-reset gate wipes the userData directory tree and
   * the user-state subtrees of ~/.cherrystudio, then resets BootConfig's
   * other keys to defaults — the app restarts as a fresh install.
   *
   * Lives under the `temp.*` top-level namespace — reserved for ephemeral
   * runtime state: single in-flight operations meant to be cleared once
   * consumed. **Never** backed up or synced.
   *
   * Lifecycle:
   *   - null: no factory reset pending (default).
   *   - { status: 'pending', userDataPath, requestedAt, attempts? }: the
   *     'app.factory_reset.request' IpcApi handler wrote this request and
   *     the next preboot should execute the wipe. `userDataPath` is the
   *     requesting instance's resolved userData directory; a gate whose
   *     resolution differs leaves the marker untouched for the owning
   *     instance (boot-config.json is shared between dev and packaged
   *     instances, which use different userData directories).
   *
   * Retry semantics: the gate durably increments `attempts` (treating
   * absence as 0) and records the wipe mode before each destructive pass,
   * clearing the marker only after a pass with no critical failures. A
   * failing pass with attempts left relaunches straight back into preboot
   * — never a writable app on a pending marker. At the cap the gate gives
   * up: marker cleared, failure surfaced in a dialog, boot continues over
   * the leftovers. There's no 'failed' state in this marker.
   *
   * Wipe mode: the gate decides how much of userData may be wiped ('tree',
   * 'owned-manifest' or 'manifest' — see decideWipeMode) on the first
   * destructive pass and records the decision here; retries reuse it. The
   * first pass deletes the ownership sentinel the decision derives from,
   * so re-deriving after a crash mid-wipe would silently downgrade a tree
   * wipe to a manifest wipe and declare success over the leftovers.
   *
   * Known limit — concurrent instances: boot-config.json is one shared
   * file written whole-file, last-writer-wins, with no re-read merge. A
   * second instance (dev and packaged coexist) that persists any key
   * during the requester's relaunch window can overwrite this marker with
   * its stale in-memory snapshot; the reset is then silently lost.
   * Fail-safe (nothing is wiped) and only reachable with two instances
   * running — re-request the reset rather than adding a merge layer.
   *
   * Consumer: src/main/core/preboot/factoryResetGate.ts
   */
  // preboot/transient/factoryReset
  'temp.factory_reset': z
    .object({
      status: z.literal('pending'),
      userDataPath: z.string(),
      requestedAt: z.string(),
      attempts: z.number().optional(),
      mode: z.enum(['tree', 'owned-manifest', 'manifest']).optional()
    })
    .nullable(),

  /**
   * In-flight relocation of the Electron userData directory tree
   * (the directory returned by `app.getPath('userData')`).
   *
   * Lives under the `temp.*` top-level namespace — reserved for ephemeral
   * runtime state: single in-flight operations meant to be cleared once
   * consumed. **Never** backed up or synced: restoring a stale temp.* entry
   * on a different machine or at a different time can cause silent data
   * corruption (e.g. re-executing a relocation that already happened).
   *
   * Lifecycle:
   *   - null: no relocation in progress (default).
   *   - { status: 'pending', taskId, from, to, copy }: the relocation
   *     request face (services/userDataRelocation) wrote this request and
   *     the next preboot should execute it.
   *   - { status: 'failed', taskId, from, to, copy, error, failedAt }:
   *     a previous preboot attempt failed. The record stays in BootConfig
   *     until the dedicated relocation window shows the error and the user
   *     explicitly abandons it by restarting on the previous userData path.
   *
   * Note: "userData" here means the Electron OS directory
   * (app.getPath('userData')), not the colloquial sense of user content.
   * The copy includes everything under that directory — user files,
   * Chromium runtime state, logs, etc.
   *
   * Consumer: src/main/services/userDataRelocation
   */
  // preboot/transient/userDataRelocation
  'temp.user_data_relocation': z
    .union([
      z.object({
        status: z.literal('pending'),
        taskId: z.uuid(),
        from: z.string(),
        to: z.string(),
        copy: z.boolean()
      }),
      z.object({
        status: z.literal('failed'),
        taskId: z.uuid(),
        from: z.string(),
        to: z.string(),
        copy: z.boolean(),
        error: z.string(),
        failedAt: z.string()
      })
    ])
    .nullable()
})

export type BootConfigSchema = z.infer<typeof bootConfigSchema>

export const DefaultBootConfig: BootConfigSchema = {
  'app.disable_hardware_acceleration': false,
  'app.user_data_path': {},
  'temp.factory_reset': null,
  'temp.user_data_relocation': null
}

// === AUTO-GENERATED CONTENT END ===
