/** Generates human and machine documentation indexes from frontmatter. */
import * as fs from 'fs'
import matter from 'gray-matter'
import * as path from 'path'

import { listMarkdownFiles } from './verify-doc-frontmatter'

const ROOT = path.resolve(__dirname, '..')

const SECTION_TITLES: Record<string, string> = {
  ai: 'AI',
  'api-gateway': 'API Gateway',
  i18n: 'i18n',
  ipc: 'IPC',
  'lan-transfer': 'LAN Transfer'
}

const titleForDomain = (domain: string): string =>
  SECTION_TITLES[domain] ??
  domain
    .split('-')
    .map((word) => word[0].toUpperCase() + word.slice(1))
    .join(' ')

/** The doc's H1 text; falls back to the filename stem when no H1 exists. */
export const docTitle = (filePath: string): string => {
  const { content } = matter(fs.readFileSync(filePath, 'utf8'))
  const heading = content.match(/^# (.+)$/m)
  return heading ? heading[1].trim() : path.basename(filePath, '.md')
}

const docDescription = (filePath: string): string => {
  const { data } = matter(fs.readFileSync(filePath, 'utf8'))
  return typeof data.description === 'string' ? data.description.trim() : ''
}

const tableRows = (docsDir: string, files: string[]): string[] =>
  files.map((file) => {
    const link = './' + path.relative(docsDir, file).split(path.sep).join('/')
    return `| [${docTitle(file)}](${link}) | ${docDescription(file)} |`
  })

const englishDocs = (dir: string): string[] =>
  listMarkdownFiles(dir).filter((file) => !file.endsWith('.zh.md') && path.basename(file) !== 'AGENTS.md')

/** README first, then alphabetical; nested files after top-level ones. */
const domainOrder = (domainDir: string, files: string[]): string[] => {
  const depth = (file: string) => file.split(path.sep).length
  return [...files].sort((a, b) => {
    const aReadme = path.dirname(a) === domainDir && path.basename(a) === 'README.md' ? 0 : 1
    const bReadme = path.dirname(b) === domainDir && path.basename(b) === 'README.md' ? 0 : 1
    return aReadme - bReadme || depth(a) - depth(b) || a.localeCompare(b)
  })
}

export const generateIndex = (repoRoot: string): string => {
  const docsDir = path.join(repoRoot, 'docs')
  const lines: string[] = [
    '# Cherry Studio Documentation',
    '',
    '<!-- Generated by scripts/gen-doc-index.ts — do not edit by hand; run `pnpm docs:index`. -->',
    '',
    '## Contrib',
    '',
    '| Document | Description |',
    '|----------|-------------|',
    '| [Contributing](../CONTRIBUTING.md) | How to contribute code |',
    ...tableRows(docsDir, englishDocs(path.join(docsDir, 'contrib'))),
    '',
    '## Documentation Governance',
    '',
    '| Document | Description |',
    '|----------|-------------|',
    ...tableRows(docsDir, englishDocs(path.join(docsDir, 'i18n'))),
    '',
    '## References'
  ]

  const referencesDir = path.join(docsDir, 'references')
  const domains = fs
    .readdirSync(referencesDir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort()

  for (const domain of domains) {
    const domainDir = path.join(referencesDir, domain)
    lines.push('', `### ${titleForDomain(domain)}`, '', '| Document | Description |', '|----------|-------------|')
    lines.push(...tableRows(docsDir, domainOrder(domainDir, englishDocs(domainDir))))
  }

  return lines.join('\n') + '\n'
}

export const generateSourcesIndex = (repoRoot: string): string => {
  const docsDir = path.join(repoRoot, 'docs')
  const files = [
    ...englishDocs(path.join(docsDir, 'contrib')),
    ...englishDocs(path.join(docsDir, 'i18n')),
    ...englishDocs(path.join(docsDir, 'references'))
  ]
  const documents = files
    .map((file) => {
      const { data } = matter(fs.readFileSync(file, 'utf8'))
      return {
        path: path.relative(repoRoot, file).split(path.sep).join('/'),
        sources: Array.isArray(data.sources)
          ? data.sources.filter((source): source is string => typeof source === 'string')
          : []
      }
    })
    .filter((document) => document.sources.length > 0)
    .map((document) => ({ ...document, sources: [...document.sources].sort() }))
    .sort((left, right) => left.path.localeCompare(right.path))
  return [
    '{',
    '  "version": 1,',
    '  "documents": [',
    ...documents.flatMap((document, index) => [
      '    {',
      `      "path": ${JSON.stringify(document.path)},`,
      `      "sources": ${JSON.stringify(document.sources)}`,
      `    }${index === documents.length - 1 ? '' : ','}`
    ]),
    '  ]',
    '}',
    ''
  ].join('\n')
}

const main = () => {
  const indexPath = path.join(ROOT, 'docs/README.md')
  const sourcesPath = path.join(ROOT, 'docs/sources-index.json')
  const generatedIndex = generateIndex(ROOT)
  const generatedSources = generateSourcesIndex(ROOT)

  if (process.argv.includes('--check')) {
    const current = fs.existsSync(indexPath) ? fs.readFileSync(indexPath, 'utf8') : ''
    const currentSources = fs.existsSync(sourcesPath) ? fs.readFileSync(sourcesPath, 'utf8') : ''
    if (current !== generatedIndex || currentSources !== generatedSources) {
      console.error('Documentation indexes are stale — run `pnpm docs:index` and commit the results.')
      process.exit(1)
    }
    console.log('Docs index OK.')
    return
  }

  fs.writeFileSync(indexPath, generatedIndex)
  fs.writeFileSync(sourcesPath, generatedSources)
  console.log('Wrote docs/README.md and docs/sources-index.json.')
}

if (require.main === module) main()
