/**
 * Generates `src/renderer/components/FileTree/iconSprite.generated.ts` — the
 * material-icon-theme sprite sheet and icon rules that `@pierre/trees` renders.
 *
 * The tree draws its rows inside a shadow root, so `@iconify/react` cannot reach
 * them. Instead the library takes an SVG string of `<symbol>` definitions plus
 * `byFileName` / `byFileExtension` rules pointing at those symbol ids. Only the
 * icons `fileIconName.ts` can actually return are emitted — bundling all 1149
 * material icons would be ~30x larger for no gain.
 *
 * Source of truth: the maps in `src/renderer/utils/fileIconName.ts` (still used
 * directly by the non-tree call sites) and `@iconify-json/material-icon-theme`.
 *
 * Run via `pnpm gen:file-tree-icons`. CI regenerates and fails on any diff,
 * mirroring the System Provider IDs guard.
 */

import * as fs from 'fs'
import * as path from 'path'

import { DEFAULT_ICON, extensionMap, filenameMap } from '../src/renderer/utils/fileIconName'

const ROOT_DIR = path.join(__dirname, '..')
const ICONS_JSON = path.join(ROOT_DIR, 'node_modules', '@iconify-json', 'material-icon-theme', 'icons.json')
const OUTPUT_FILE = path.join(ROOT_DIR, 'src', 'renderer', 'components', 'FileTree', 'iconSprite.generated.ts')

/** Prefix keeping our symbol ids out of the library's `file-tree-*` namespace. */
const SYMBOL_PREFIX = 'mit-'

interface IconifyIcon {
  body: string
  width?: number
  height?: number
}

interface IconifyJson {
  icons: Record<string, IconifyIcon>
  aliases?: Record<string, { parent: string }>
  width?: number
  height?: number
}

function resolveIcon(json: IconifyJson, name: string): { icon: IconifyIcon; width: number; height: number } | null {
  const alias = json.aliases?.[name]
  const icon = json.icons[name] ?? (alias ? json.icons[alias.parent] : undefined)
  if (!icon) return null
  return {
    icon,
    width: icon.width ?? json.width ?? 24,
    height: icon.height ?? json.height ?? 24
  }
}

/** Every icon name `getFileIconName` can return. */
export function collectIconNames(): string[] {
  const names = new Set<string>([...Object.values(filenameMap), ...Object.values(extensionMap), DEFAULT_ICON])
  return Array.from(names).sort()
}

export interface SpriteResult {
  sprite: string
  /** Names the maps reference that material-icon-theme does not ship. */
  unknown: string[]
}

/**
 * Names absent from material-icon-theme are skipped rather than fatal: they
 * already render as an empty `<Icon>` today, so dropping them keeps the tree
 * pixel-identical and leaves the map fix as its own change. `unknown` is
 * reported by the CLI and recorded in the generated header so it stays visible.
 */
export function buildSprite(json: IconifyJson, names: readonly string[]): SpriteResult {
  const symbols: string[] = []
  const unknown: string[] = []
  for (const name of names) {
    const resolved = resolveIcon(json, name)
    if (!resolved) {
      unknown.push(name)
      continue
    }
    const { icon, width, height } = resolved
    symbols.push(`<symbol id="${SYMBOL_PREFIX}${name}" viewBox="0 0 ${width} ${height}">${icon.body}</symbol>`)
  }
  return {
    sprite: `<svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" style="display:none">${symbols.join('')}</svg>`,
    unknown
  }
}

/**
 * `byFileName` and `byFileExtension` keys are lowercased by the library's
 * resolver, so case variants in the source maps collapse here — that matches
 * `getFileIconName`, which also falls back to a lowercased lookup. Rules whose
 * icon is not in the sprite are dropped so the row falls back to the generic
 * file slot instead of pointing `<use>` at a missing symbol.
 */
function toRuleTable(source: Record<string, string>, unknown: ReadonlySet<string>): Record<string, string> {
  const table: Record<string, string> = {}
  for (const [key, icon] of Object.entries(source)) {
    if (unknown.has(icon)) continue
    table[key.toLowerCase()] = `${SYMBOL_PREFIX}${icon}`
  }
  return table
}

function serializeTable(table: Record<string, string>): string {
  const entries = Object.entries(table)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([key, value]) => `  ${JSON.stringify(key)}: ${JSON.stringify(value)}`)
  return `{\n${entries.join(',\n')}\n}`
}

export function buildOutput(json: IconifyJson): string {
  const names = collectIconNames()
  const { sprite, unknown } = buildSprite(json, names)
  const unknownSet = new Set(unknown)
  const unknownNote =
    unknown.length === 0
      ? ''
      : `//\n// Skipped — material-icon-theme ships no such icon, so these already render blank\n// via @iconify/react today: ${unknown.join(', ')}\n`

  return `// Generated by scripts/generate-file-tree-icon-sprite.ts. Do not edit by hand.
// Run \`pnpm file-tree:icons:generate\` after changing the maps in src/renderer/utils/fileIconName.ts.
${unknownNote}
/** \`<symbol>\` definitions injected into the tree's shadow root as \`icons.spriteSheet\`. */
export const FILE_TREE_ICON_SPRITE = ${JSON.stringify(sprite)}

/** Exact basename → symbol id. Mirrors \`filenameMap\`. */
export const FILE_TREE_ICON_BY_FILE_NAME: Record<string, string> = ${serializeTable(toRuleTable(filenameMap, unknownSet))}

/** Extension (no leading dot; \`d.ts\` beats \`ts\`) → symbol id. Mirrors \`extensionMap\`. */
export const FILE_TREE_ICON_BY_FILE_EXTENSION: Record<string, string> = ${serializeTable(toRuleTable(extensionMap, unknownSet))}

/** Built-in slot overrides. Only the generic file icon needs one. */
export const FILE_TREE_ICON_REMAP: Record<string, string> = {
  'file-tree-icon-file': ${JSON.stringify(`${SYMBOL_PREFIX}${DEFAULT_ICON}`)}
}
`
}

function main(): void {
  const json = JSON.parse(fs.readFileSync(ICONS_JSON, 'utf8')) as IconifyJson
  const output = buildOutput(json)
  const { unknown } = buildSprite(json, collectIconNames())
  if (unknown.length > 0) {
    console.warn(`Skipped ${unknown.length} icon(s) missing from material-icon-theme: ${unknown.join(', ')}`)
  }
  fs.writeFileSync(OUTPUT_FILE, output)
  console.log(`Wrote ${path.relative(ROOT_DIR, OUTPUT_FILE)} (${collectIconNames().length - unknown.length} icons).`)
}

if (require.main === module) {
  main()
}
