/**
 * Auto-generated icon catalog for runtime lookup
 * Do not edit manually — regenerated by the icon pipeline
 *
 * Generated at: 2026-02-18T17:04:22.020Z
 * Total icons: 113
 */
import { type CompoundIcon } from '../types'
import { Ai302Icon } from './302ai'
import { Ai21Icon } from './ai21'
import { AihubmixIcon } from './aihubmix'
import { AionlabsIcon } from './aionlabs'
import { AiOnlyIcon } from './aiOnly'
import { AlayanewIcon } from './alayanew'
import { AllenaiIcon } from './allenai'
import { AnthropicIcon } from './anthropic'
import { ArceeAiIcon } from './arceeAi'
import { AwsBedrockIcon } from './awsBedrock'
import { AzureaiIcon } from './azureai'
import { BaaiIcon } from './baai'
import { BaichuanIcon } from './baichuan'
import { BaiduCloudIcon } from './baiduCloud'
import { BailianIcon } from './bailian'
import { BflIcon } from './bfl'
import { BochaIcon } from './bocha'
import { BurncloudIcon } from './burncloud'
import { BytedanceIcon } from './bytedance'
import { CephalonIcon } from './cephalon'
import { CerebrasIcon } from './cerebras'
import { CherryinIcon } from './cherryin'
import { CloudflareIcon } from './cloudflare'
import { CohereIcon } from './cohere'
import { DashscopeIcon } from './dashscope'
import { DatabricksIcon } from './databricks'
import { DeepcogitoIcon } from './deepcogito'
import { DeepseekIcon } from './deepseek'
import { DmxapiIcon } from './dmxapi'
import { Doc2xIcon } from './doc2x'
import { DolphinAiIcon } from './dolphinAi'
import { ElevenlabsIcon } from './elevenlabs'
import { EssentialAiIcon } from './essentialAi'
import { ExaIcon } from './exa'
import { FireworksIcon } from './fireworks'
import { GiteeAiIcon } from './giteeAi'
import { GithubIcon } from './github'
import { GoogleIcon } from './google'
import { GpustackIcon } from './gpustack'
import { GraphRagIcon } from './graphRag'
import { GrokIcon } from './grok'
import { GroqIcon } from './groq'
import { HuggingfaceIcon } from './huggingface'
import { HyperbolicIcon } from './hyperbolic'
import { IdeogramIcon } from './ideogram'
import { InceptionlabsIcon } from './inceptionlabs'
import { InfiniIcon } from './infini'
import { InflectionIcon } from './inflection'
import { IntelIcon } from './intel'
import { InternlmIcon } from './internlm'
import { JimengIcon } from './jimeng'
import { JinaIcon } from './jina'
import { KlingIcon } from './kling'
import { KwaipilotIcon } from './kwaipilot'
import { LanyunIcon } from './lanyun'
import { LeptonIcon } from './lepton'
import { LiquidIcon } from './liquid'
import { LmstudioIcon } from './lmstudio'
import { LongcatIcon } from './longcat'
import { MacosIcon } from './macos'
import { McprouterIcon } from './mcprouter'
import { MetaIcon } from './meta'
import { MineruIcon } from './mineru'
import { MinimaxIcon } from './minimax'
import { MistralIcon } from './mistral'
import { MixedbreadIcon } from './mixedbread'
import { ModelscopeIcon } from './modelscope'
import { MoonshotIcon } from './moonshot'
import { NeteaseYoudaoIcon } from './neteaseYoudao'
import { NewapiIcon } from './newapi'
import { NomicIcon } from './nomic'
import { NousresearchIcon } from './nousresearch'
import { NvidiaIcon } from './nvidia'
import { O3Icon } from './o3'
import { OcoolaiIcon } from './ocoolai'
import { OllamaIcon } from './ollama'
import { OpenaiIcon } from './openai'
import { OpenrouterIcon } from './openrouter'
import { PaddleocrIcon } from './paddleocr'
import { PerplexityIcon } from './perplexity'
import { Ph8Icon } from './ph8'
import { PoeIcon } from './poe'
import { PpioIcon } from './ppio'
import { QiniuIcon } from './qiniu'
import { RecraftIcon } from './recraft'
import { RelaceIcon } from './relace'
import { RiverflowIcon } from './riverflow'
import { RunawayIcon } from './runaway'
import { SearxngIcon } from './searxng'
import { SiliconIcon } from './silicon'
import { SophnetIcon } from './sophnet'
import { StablilityIcon } from './stablility'
import { StepIcon } from './step'
import { StreamlakeIcon } from './streamlake'
import { SunoIcon } from './suno'
import { TavilyIcon } from './tavily'
import { TencentCloudTiIcon } from './tencentCloudTi'
import { TesseractJsIcon } from './tesseractJs'
import { TngIcon } from './tng'
import { TogetherIcon } from './together'
import { TokenfluxIcon } from './tokenflux'
import { UpstageIcon } from './upstage'
import { VercelIcon } from './vercel'
import { VertexaiIcon } from './vertexai'
import { ViduIcon } from './vidu'
import { VolcengineIcon } from './volcengine'
import { VoyageIcon } from './voyage'
import { WenxinIcon } from './wenxin'
import { WorkersAiIcon } from './workersAi'
import { XirangIcon } from './xirang'
import { ZAiIcon } from './zAi'
import { ZeroOneIcon } from './zeroOne'
import { ZhipuIcon } from './zhipu'

export const PROVIDER_ICON_CATALOG: Record<string, CompoundIcon> = {
  '302ai': Ai302Icon,
  ai21: Ai21Icon,
  aiOnly: AiOnlyIcon,
  aihubmix: AihubmixIcon,
  aionlabs: AionlabsIcon,
  alayanew: AlayanewIcon,
  allenai: AllenaiIcon,
  anthropic: AnthropicIcon,
  arceeAi: ArceeAiIcon,
  awsBedrock: AwsBedrockIcon,
  azureai: AzureaiIcon,
  baai: BaaiIcon,
  baichuan: BaichuanIcon,
  baiduCloud: BaiduCloudIcon,
  bailian: BailianIcon,
  bfl: BflIcon,
  bocha: BochaIcon,
  burncloud: BurncloudIcon,
  bytedance: BytedanceIcon,
  cephalon: CephalonIcon,
  cerebras: CerebrasIcon,
  cherryin: CherryinIcon,
  cloudflare: CloudflareIcon,
  cohere: CohereIcon,
  dashscope: DashscopeIcon,
  databricks: DatabricksIcon,
  deepcogito: DeepcogitoIcon,
  deepseek: DeepseekIcon,
  dmxapi: DmxapiIcon,
  doc2x: Doc2xIcon,
  dolphinAi: DolphinAiIcon,
  elevenlabs: ElevenlabsIcon,
  essentialAi: EssentialAiIcon,
  exa: ExaIcon,
  fireworks: FireworksIcon,
  giteeAi: GiteeAiIcon,
  github: GithubIcon,
  google: GoogleIcon,
  gpustack: GpustackIcon,
  graphRag: GraphRagIcon,
  grok: GrokIcon,
  groq: GroqIcon,
  huggingface: HuggingfaceIcon,
  hyperbolic: HyperbolicIcon,
  ideogram: IdeogramIcon,
  inceptionlabs: InceptionlabsIcon,
  infini: InfiniIcon,
  inflection: InflectionIcon,
  intel: IntelIcon,
  internlm: InternlmIcon,
  jimeng: JimengIcon,
  jina: JinaIcon,
  kling: KlingIcon,
  kwaipilot: KwaipilotIcon,
  lanyun: LanyunIcon,
  lepton: LeptonIcon,
  liquid: LiquidIcon,
  lmstudio: LmstudioIcon,
  longcat: LongcatIcon,
  macos: MacosIcon,
  mcprouter: McprouterIcon,
  meta: MetaIcon,
  mineru: MineruIcon,
  minimax: MinimaxIcon,
  mistral: MistralIcon,
  mixedbread: MixedbreadIcon,
  modelscope: ModelscopeIcon,
  moonshot: MoonshotIcon,
  neteaseYoudao: NeteaseYoudaoIcon,
  newapi: NewapiIcon,
  nomic: NomicIcon,
  nousresearch: NousresearchIcon,
  nvidia: NvidiaIcon,
  o3: O3Icon,
  ocoolai: OcoolaiIcon,
  ollama: OllamaIcon,
  openai: OpenaiIcon,
  openrouter: OpenrouterIcon,
  paddleocr: PaddleocrIcon,
  perplexity: PerplexityIcon,
  ph8: Ph8Icon,
  poe: PoeIcon,
  ppio: PpioIcon,
  qiniu: QiniuIcon,
  recraft: RecraftIcon,
  relace: RelaceIcon,
  riverflow: RiverflowIcon,
  runaway: RunawayIcon,
  searxng: SearxngIcon,
  silicon: SiliconIcon,
  sophnet: SophnetIcon,
  stablility: StablilityIcon,
  step: StepIcon,
  streamlake: StreamlakeIcon,
  suno: SunoIcon,
  tavily: TavilyIcon,
  tencentCloudTi: TencentCloudTiIcon,
  tesseractJs: TesseractJsIcon,
  tng: TngIcon,
  together: TogetherIcon,
  tokenflux: TokenfluxIcon,
  upstage: UpstageIcon,
  vercel: VercelIcon,
  vertexai: VertexaiIcon,
  vidu: ViduIcon,
  volcengine: VolcengineIcon,
  voyage: VoyageIcon,
  wenxin: WenxinIcon,
  workersAi: WorkersAiIcon,
  xirang: XirangIcon,
  zAi: ZAiIcon,
  zeroOne: ZeroOneIcon,
  zhipu: ZhipuIcon
}
