import path from 'node:path'

import { describe, expect, it } from 'vitest'

import { buildThemeContractCss, loadThemeContractInputs } from '../build-theme-css'

describe('buildThemeContractCss', () => {
  it('maps token sources into the public theme contract', async () => {
    const stylesDir = path.resolve(import.meta.dirname, '../../src/styles')
    const css = buildThemeContractCss(await loadThemeContractInputs(stylesDir))

    expect(css).toContain("@import './tokens.css';")
    expect(css).toContain('/* Runtime Theme Inputs */')
    expect(css).not.toContain('--cs-theme-primary')
    expect(css).not.toContain('--cs-theme-ring')
    expect(css).toContain('--color-theme-accent: var(--cs-theme-accent);')
    expect(css).toContain('--color-theme-accent-text: var(--cs-theme-accent-text);')
    expect(css).toContain('--color-theme-accent-foreground: var(--cs-theme-accent-foreground);')
    expect(css).not.toContain('--cs-user-font-family:')
    expect(css).not.toContain('--cs-user-code-font-family:')
    expect(css).toContain('/* Compatibility Aliases */')
    expect(css).toContain('--primary: var(--color-primary);')
    expect(css).toContain('--ring: var(--color-ring);')
    expect(css).toContain('--color-muted-foreground: var(--cs-foreground-secondary-solid);')
    expect(css).not.toContain('--cs-muted-foreground')
    expect(css).toContain('--color-neutral-50: var(--cs-neutral-50);')
    expect(css).toContain('--color-brand-500: var(--cs-brand-500);')
    expect(css).toContain('/* Semantic Colors */')
    expect(css).toContain('--color-primary: var(--cs-primary);')
    expect(css).not.toContain('--color-primary: var(--cs-theme-primary);')
    expect(css).toContain('--color-primary-soft: var(--cs-primary-soft);')
    expect(css).toContain('--color-primary-mute: var(--cs-primary-mute);')
    expect(css).not.toContain('--color-theme-accent-soft')
    expect(css).toContain('--color-control-accent: var(--cs-control-accent);')
    expect(css).toContain('--color-control-accent-hover: var(--cs-control-accent-hover);')
    expect(css).toContain('--color-control-accent-foreground: var(--cs-control-accent-foreground);')
    expect(css).toContain('--color-link: var(--cs-link);')
    expect(css).toContain('--color-ring: var(--cs-ring);')
    expect(css).toContain('--color-destructive: var(--cs-destructive);')
    expect(css).toContain('--color-error-base: var(--cs-error-base);')
    expect(css).not.toContain('/* Component Slots')
    expect(css).not.toContain('--color-button-elevated-from')
    expect(css).not.toContain('--color-switch-thumb')
    expect(css).not.toContain('--color-badge-highlight-border')
    expect(css).toContain('--radius-md: var(--cs-radius-md);')
    expect(css).toContain('--font-size-body-md: var(--cs-font-size-body-md);')
    expect(css).toContain('/* Iconography */')
    expect(css).toContain('--icon-stroke: var(--cs-icon-stroke);')
    expect(css).toContain('--animate-checkbox-bounce: checkbox-bounce 300ms cubic-bezier(0.4, 0, 0.2, 1);')
    expect(css).toContain('--animate-checkbox-icon-in: checkbox-icon-in 160ms ease-out both;')
    expect(css).toContain('@keyframes checkbox-bounce {')
    expect(css).toContain('@keyframes checkbox-icon-in {')
    expect(css).not.toContain('.dark {')
    expect(css).not.toContain('color-mix(')
  })
})
